DELETE FROM recipe_categories WHERE name IN (
    'Veggie',
    'Batch',
    'Thai',
    'Sweet Treats',
    'Easy',
    'Air Fryer',
    'American',
    'Mexican',
    'Party',
    'Meaty',
    'Breakfast',
    'Chutneys and Sauces',
    'Healthy',
    'Italian',
    'Speedy',
    'Fun',
    'Group',
    'Salads',
    'Baking',
    'Asian',
    'Lunch',
    'Fishy',
    'One Tray',
    'Roast',
    'Starters',
    'Spicy',
    'Drinks',
    'Side Dishes'
);
