INSERT INTO recipe_categories (name) VALUES
    ('Veggie'),
    ('Batch'),
    ('Thai'),
    ('Sweet Treats'),
    ('Easy'),
    ('Air Fryer'),
    ('American'),
    ('Mexican'),
    ('Party'),
    ('Meaty'),
    ('Breakfast'),
    ('Chutneys and Sauces'),
    ('Healthy'),
    ('Italian'),
    ('Speedy'),
    ('Fun'),
    ('Group'),
    ('Salads'),
    ('Baking'),
    ('Asian'),
    ('Lunch'),
    ('Fishy'),
    ('One Tray'),
    ('Roast'),
    ('Starters'),
    ('Spicy'),
    ('Drinks'),
    ('Side Dishes')
ON CONFLICT (name) DO NOTHING;
