// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"
)

// MockMenuRepository is an autogenerated mock type for the MenuRepository type
type MockMenuRepository struct {
	mock.Mock
}

type MockMenuRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMenuRepository) EXPECT() *MockMenuRepository_Expecter {
	return &MockMenuRepository_Expecter{mock: &_m.Mock}
}

// GetMenu provides a mock function with given fields: ctx, userID
func (_m *MockMenuRepository) GetMenu(ctx context.Context, userID string) (*models.Menu, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMenu")
	}

	var r0 *models.Menu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Menu, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Menu); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Menu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMenuRepository_GetMenu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMenu'
type MockMenuRepository_GetMenu_Call struct {
	*mock.Call
}

// GetMenu is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMenuRepository_Expecter) GetMenu(ctx interface{}, userID interface{}) *MockMenuRepository_GetMenu_Call {
	return &MockMenuRepository_GetMenu_Call{Call: _e.mock.On("GetMenu", ctx, userID)}
}

func (_c *MockMenuRepository_GetMenu_Call) Run(run func(ctx context.Context, userID string)) *MockMenuRepository_GetMenu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMenuRepository_GetMenu_Call) Return(_a0 *models.Menu, _a1 error) *MockMenuRepository_GetMenu_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMenuRepository_GetMenu_Call) RunAndReturn(run func(context.Context, string) (*models.Menu, error)) *MockMenuRepository_GetMenu_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveEntry provides a mock function with given fields: ctx, userID, recipeID
func (_m *MockMenuRepository) RemoveEntry(ctx context.Context, userID string, recipeID string) error {
	ret := _m.Called(ctx, userID, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, recipeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMenuRepository_RemoveEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveEntry'
type MockMenuRepository_RemoveEntry_Call struct {
	*mock.Call
}

// RemoveEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - recipeID string
func (_e *MockMenuRepository_Expecter) RemoveEntry(ctx interface{}, userID interface{}, recipeID interface{}) *MockMenuRepository_RemoveEntry_Call {
	return &MockMenuRepository_RemoveEntry_Call{Call: _e.mock.On("RemoveEntry", ctx, userID, recipeID)}
}

func (_c *MockMenuRepository_RemoveEntry_Call) Run(run func(ctx context.Context, userID string, recipeID string)) *MockMenuRepository_RemoveEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMenuRepository_RemoveEntry_Call) Return(_a0 error) *MockMenuRepository_RemoveEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMenuRepository_RemoveEntry_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMenuRepository_RemoveEntry_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEntryServes provides a mock function with given fields: ctx, userID, recipeID, serves
func (_m *MockMenuRepository) UpdateEntryServes(ctx context.Context, userID string, recipeID string, serves int) error {
	ret := _m.Called(ctx, userID, recipeID, serves)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEntryServes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, userID, recipeID, serves)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMenuRepository_UpdateEntryServes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEntryServes'
type MockMenuRepository_UpdateEntryServes_Call struct {
	*mock.Call
}

// UpdateEntryServes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - recipeID string
//   - serves int
func (_e *MockMenuRepository_Expecter) UpdateEntryServes(ctx interface{}, userID interface{}, recipeID interface{}, serves interface{}) *MockMenuRepository_UpdateEntryServes_Call {
	return &MockMenuRepository_UpdateEntryServes_Call{Call: _e.mock.On("UpdateEntryServes", ctx, userID, recipeID, serves)}
}

func (_c *MockMenuRepository_UpdateEntryServes_Call) Run(run func(ctx context.Context, userID string, recipeID string, serves int)) *MockMenuRepository_UpdateEntryServes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockMenuRepository_UpdateEntryServes_Call) Return(_a0 error) *MockMenuRepository_UpdateEntryServes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMenuRepository_UpdateEntryServes_Call) RunAndReturn(run func(context.Context, string, string, int) error) *MockMenuRepository_UpdateEntryServes_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertEntry provides a mock function with given fields: ctx, userID, recipeID, serves, callerIsAdmin
func (_m *MockMenuRepository) UpsertEntry(ctx context.Context, userID string, recipeID string, serves int, callerIsAdmin bool) error {
	ret := _m.Called(ctx, userID, recipeID, serves, callerIsAdmin)

	if len(ret) == 0 {
		panic("no return value specified for UpsertEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, bool) error); ok {
		r0 = rf(ctx, userID, recipeID, serves, callerIsAdmin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMenuRepository_UpsertEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertEntry'
type MockMenuRepository_UpsertEntry_Call struct {
	*mock.Call
}

// UpsertEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - recipeID string
//   - serves int
//   - callerIsAdmin bool
func (_e *MockMenuRepository_Expecter) UpsertEntry(ctx interface{}, userID interface{}, recipeID interface{}, serves interface{}, callerIsAdmin interface{}) *MockMenuRepository_UpsertEntry_Call {
	return &MockMenuRepository_UpsertEntry_Call{Call: _e.mock.On("UpsertEntry", ctx, userID, recipeID, serves, callerIsAdmin)}
}

func (_c *MockMenuRepository_UpsertEntry_Call) Run(run func(ctx context.Context, userID string, recipeID string, serves int, callerIsAdmin bool)) *MockMenuRepository_UpsertEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(bool))
	})
	return _c
}

func (_c *MockMenuRepository_UpsertEntry_Call) Return(_a0 error) *MockMenuRepository_UpsertEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMenuRepository_UpsertEntry_Call) RunAndReturn(run func(context.Context, string, string, int, bool) error) *MockMenuRepository_UpsertEntry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMenuRepository creates a new instance of MockMenuRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMenuRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMenuRepository {
	mock := &MockMenuRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
