// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"
)

// MockItemCategoryRepository is an autogenerated mock type for the ItemCategoryRepository type
type MockItemCategoryRepository struct {
	mock.Mock
}

type MockItemCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemCategoryRepository) EXPECT() *MockItemCategoryRepository_Expecter {
	return &MockItemCategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name, icon
func (_m *MockItemCategoryRepository) Create(ctx context.Context, name string, icon string) (*models.ItemCategory, error) {
	ret := _m.Called(ctx, name, icon)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.ItemCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.ItemCategory, error)); ok {
		return rf(ctx, name, icon)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.ItemCategory); ok {
		r0 = rf(ctx, name, icon)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ItemCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, icon)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockItemCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - icon string
func (_e *MockItemCategoryRepository_Expecter) Create(ctx interface{}, name interface{}, icon interface{}) *MockItemCategoryRepository_Create_Call {
	return &MockItemCategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, name, icon)}
}

func (_c *MockItemCategoryRepository_Create_Call) Run(run func(ctx context.Context, name string, icon string)) *MockItemCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockItemCategoryRepository_Create_Call) Return(_a0 *models.ItemCategory, _a1 error) *MockItemCategoryRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemCategoryRepository_Create_Call) RunAndReturn(run func(context.Context, string, string) (*models.ItemCategory, error)) *MockItemCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockItemCategoryRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockItemCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockItemCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockItemCategoryRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockItemCategoryRepository_Delete_Call {
	return &MockItemCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockItemCategoryRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockItemCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockItemCategoryRepository_Delete_Call) Return(_a0 error) *MockItemCategoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockItemCategoryRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockItemCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockItemCategoryRepository) List(ctx context.Context) ([]*models.ItemCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.ItemCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.ItemCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.ItemCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ItemCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemCategoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockItemCategoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockItemCategoryRepository_Expecter) List(ctx interface{}) *MockItemCategoryRepository_List_Call {
	return &MockItemCategoryRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockItemCategoryRepository_List_Call) Run(run func(ctx context.Context)) *MockItemCategoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockItemCategoryRepository_List_Call) Return(_a0 []*models.ItemCategory, _a1 error) *MockItemCategoryRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemCategoryRepository_List_Call) RunAndReturn(run func(context.Context) ([]*models.ItemCategory, error)) *MockItemCategoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name, icon
func (_m *MockItemCategoryRepository) Update(ctx context.Context, id string, name string, icon string) (*models.ItemCategory, error) {
	ret := _m.Called(ctx, id, name, icon)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.ItemCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.ItemCategory, error)); ok {
		return rf(ctx, id, name, icon)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.ItemCategory); ok {
		r0 = rf(ctx, id, name, icon)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ItemCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, id, name, icon)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockItemCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
//   - icon string
func (_e *MockItemCategoryRepository_Expecter) Update(ctx interface{}, id interface{}, name interface{}, icon interface{}) *MockItemCategoryRepository_Update_Call {
	return &MockItemCategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, name, icon)}
}

func (_c *MockItemCategoryRepository_Update_Call) Run(run func(ctx context.Context, id string, name string, icon string)) *MockItemCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockItemCategoryRepository_Update_Call) Return(_a0 *models.ItemCategory, _a1 error) *MockItemCategoryRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemCategoryRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.ItemCategory, error)) *MockItemCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemCategoryRepository creates a new instance of MockItemCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemCategoryRepository {
	mock := &MockItemCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
