// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"
)

// MockAccountUserRepository is an autogenerated mock type for the AccountUserRepository type
type MockAccountUserRepository struct {
	mock.Mock
}

type MockAccountUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountUserRepository) EXPECT() *MockAccountUserRepository_Expecter {
	return &MockAccountUserRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, userID
func (_m *MockAccountUserRepository) Delete(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountUserRepository_Expecter) Delete(ctx interface{}, userID interface{}) *MockAccountUserRepository_Delete_Call {
	return &MockAccountUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID)}
}

func (_c *MockAccountUserRepository_Delete_Call) Run(run func(ctx context.Context, userID string)) *MockAccountUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountUserRepository_Delete_Call) Return(_a0 error) *MockAccountUserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUserRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockAccountUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDForUpdate provides a mock function with given fields: ctx, userID
func (_m *MockAccountUserRepository) FindByIDForUpdate(ctx context.Context, userID string) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDForUpdate")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountUserRepository_FindByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDForUpdate'
type MockAccountUserRepository_FindByIDForUpdate_Call struct {
	*mock.Call
}

// FindByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountUserRepository_Expecter) FindByIDForUpdate(ctx interface{}, userID interface{}) *MockAccountUserRepository_FindByIDForUpdate_Call {
	return &MockAccountUserRepository_FindByIDForUpdate_Call{Call: _e.mock.On("FindByIDForUpdate", ctx, userID)}
}

func (_c *MockAccountUserRepository_FindByIDForUpdate_Call) Run(run func(ctx context.Context, userID string)) *MockAccountUserRepository_FindByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountUserRepository_FindByIDForUpdate_Call) Return(_a0 *models.User, _a1 error) *MockAccountUserRepository_FindByIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountUserRepository_FindByIDForUpdate_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockAccountUserRepository_FindByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountUserRepository creates a new instance of MockAccountUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountUserRepository {
	mock := &MockAccountUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
