// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"
)

// MockRecipeRepository is an autogenerated mock type for the RecipeRepository type
type MockRecipeRepository struct {
	mock.Mock
}

type MockRecipeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecipeRepository) EXPECT() *MockRecipeRepository_Expecter {
	return &MockRecipeRepository_Expecter{mock: &_m.Mock}
}

// AddFavourite provides a mock function with given fields: ctx, userID, recipeID, callerIsAdmin
func (_m *MockRecipeRepository) AddFavourite(ctx context.Context, userID string, recipeID string, callerIsAdmin bool) error {
	ret := _m.Called(ctx, userID, recipeID, callerIsAdmin)

	if len(ret) == 0 {
		panic("no return value specified for AddFavourite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, userID, recipeID, callerIsAdmin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRecipeRepository_AddFavourite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFavourite'
type MockRecipeRepository_AddFavourite_Call struct {
	*mock.Call
}

// AddFavourite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - recipeID string
//   - callerIsAdmin bool
func (_e *MockRecipeRepository_Expecter) AddFavourite(ctx interface{}, userID interface{}, recipeID interface{}, callerIsAdmin interface{}) *MockRecipeRepository_AddFavourite_Call {
	return &MockRecipeRepository_AddFavourite_Call{Call: _e.mock.On("AddFavourite", ctx, userID, recipeID, callerIsAdmin)}
}

func (_c *MockRecipeRepository_AddFavourite_Call) Run(run func(ctx context.Context, userID string, recipeID string, callerIsAdmin bool)) *MockRecipeRepository_AddFavourite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockRecipeRepository_AddFavourite_Call) Return(_a0 error) *MockRecipeRepository_AddFavourite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRecipeRepository_AddFavourite_Call) RunAndReturn(run func(context.Context, string, string, bool) error) *MockRecipeRepository_AddFavourite_Call {
	_c.Call.Return(run)
	return _c
}

// CountByCreator provides a mock function with given fields: ctx, userID
func (_m *MockRecipeRepository) CountByCreator(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByCreator")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecipeRepository_CountByCreator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByCreator'
type MockRecipeRepository_CountByCreator_Call struct {
	*mock.Call
}

// CountByCreator is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRecipeRepository_Expecter) CountByCreator(ctx interface{}, userID interface{}) *MockRecipeRepository_CountByCreator_Call {
	return &MockRecipeRepository_CountByCreator_Call{Call: _e.mock.On("CountByCreator", ctx, userID)}
}

func (_c *MockRecipeRepository_CountByCreator_Call) Run(run func(ctx context.Context, userID string)) *MockRecipeRepository_CountByCreator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRecipeRepository_CountByCreator_Call) Return(_a0 int, _a1 error) *MockRecipeRepository_CountByCreator_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecipeRepository_CountByCreator_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockRecipeRepository_CountByCreator_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, input
func (_m *MockRecipeRepository) Create(ctx context.Context, input models.CreateRecipeInput) (*models.Recipe, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateRecipeInput) (*models.Recipe, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateRecipeInput) *models.Recipe); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateRecipeInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecipeRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRecipeRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateRecipeInput
func (_e *MockRecipeRepository_Expecter) Create(ctx interface{}, input interface{}) *MockRecipeRepository_Create_Call {
	return &MockRecipeRepository_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockRecipeRepository_Create_Call) Run(run func(ctx context.Context, input models.CreateRecipeInput)) *MockRecipeRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateRecipeInput))
	})
	return _c
}

func (_c *MockRecipeRepository_Create_Call) Return(_a0 *models.Recipe, _a1 error) *MockRecipeRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecipeRepository_Create_Call) RunAndReturn(run func(context.Context, models.CreateRecipeInput) (*models.Recipe, error)) *MockRecipeRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id, callerID, callerIsAdmin
func (_m *MockRecipeRepository) GetByID(ctx context.Context, id string, callerID *string, callerIsAdmin bool) (*models.RecipeDetail, error) {
	ret := _m.Called(ctx, id, callerID, callerIsAdmin)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.RecipeDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, bool) (*models.RecipeDetail, error)); ok {
		return rf(ctx, id, callerID, callerIsAdmin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, bool) *models.RecipeDetail); ok {
		r0 = rf(ctx, id, callerID, callerIsAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RecipeDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, bool) error); ok {
		r1 = rf(ctx, id, callerID, callerIsAdmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecipeRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRecipeRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - callerID *string
//   - callerIsAdmin bool
func (_e *MockRecipeRepository_Expecter) GetByID(ctx interface{}, id interface{}, callerID interface{}, callerIsAdmin interface{}) *MockRecipeRepository_GetByID_Call {
	return &MockRecipeRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, callerID, callerIsAdmin)}
}

func (_c *MockRecipeRepository_GetByID_Call) Run(run func(ctx context.Context, id string, callerID *string, callerIsAdmin bool)) *MockRecipeRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(bool))
	})
	return _c
}

func (_c *MockRecipeRepository_GetByID_Call) Return(_a0 *models.RecipeDetail, _a1 error) *MockRecipeRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecipeRepository_GetByID_Call) RunAndReturn(run func(context.Context, string, *string, bool) (*models.RecipeDetail, error)) *MockRecipeRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimeRange provides a mock function with given fields: ctx
func (_m *MockRecipeRepository) GetTimeRange(ctx context.Context) (*models.RecipeTimeRange, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeRange")
	}

	var r0 *models.RecipeTimeRange
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.RecipeTimeRange, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.RecipeTimeRange); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RecipeTimeRange)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecipeRepository_GetTimeRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimeRange'
type MockRecipeRepository_GetTimeRange_Call struct {
	*mock.Call
}

// GetTimeRange is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRecipeRepository_Expecter) GetTimeRange(ctx interface{}) *MockRecipeRepository_GetTimeRange_Call {
	return &MockRecipeRepository_GetTimeRange_Call{Call: _e.mock.On("GetTimeRange", ctx)}
}

func (_c *MockRecipeRepository_GetTimeRange_Call) Run(run func(ctx context.Context)) *MockRecipeRepository_GetTimeRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRecipeRepository_GetTimeRange_Call) Return(_a0 *models.RecipeTimeRange, _a1 error) *MockRecipeRepository_GetTimeRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecipeRepository_GetTimeRange_Call) RunAndReturn(run func(context.Context) (*models.RecipeTimeRange, error)) *MockRecipeRepository_GetTimeRange_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockRecipeRepository) List(ctx context.Context, filter models.RecipeListFilter) ([]*models.RecipeCard, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.RecipeCard
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.RecipeListFilter) ([]*models.RecipeCard, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.RecipeListFilter) []*models.RecipeCard); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.RecipeCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.RecipeListFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.RecipeListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRecipeRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRecipeRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter models.RecipeListFilter
func (_e *MockRecipeRepository_Expecter) List(ctx interface{}, filter interface{}) *MockRecipeRepository_List_Call {
	return &MockRecipeRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockRecipeRepository_List_Call) Run(run func(ctx context.Context, filter models.RecipeListFilter)) *MockRecipeRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.RecipeListFilter))
	})
	return _c
}

func (_c *MockRecipeRepository_List_Call) Return(_a0 []*models.RecipeCard, _a1 int, _a2 error) *MockRecipeRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRecipeRepository_List_Call) RunAndReturn(run func(context.Context, models.RecipeListFilter) ([]*models.RecipeCard, int, error)) *MockRecipeRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListFavourites provides a mock function with given fields: ctx, userID, page, limit
func (_m *MockRecipeRepository) ListFavourites(ctx context.Context, userID string, page int, limit int) ([]*models.RecipeCard, int, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListFavourites")
	}

	var r0 []*models.RecipeCard
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*models.RecipeCard, int, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*models.RecipeCard); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.RecipeCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, userID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRecipeRepository_ListFavourites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFavourites'
type MockRecipeRepository_ListFavourites_Call struct {
	*mock.Call
}

// ListFavourites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int
//   - limit int
func (_e *MockRecipeRepository_Expecter) ListFavourites(ctx interface{}, userID interface{}, page interface{}, limit interface{}) *MockRecipeRepository_ListFavourites_Call {
	return &MockRecipeRepository_ListFavourites_Call{Call: _e.mock.On("ListFavourites", ctx, userID, page, limit)}
}

func (_c *MockRecipeRepository_ListFavourites_Call) Run(run func(ctx context.Context, userID string, page int, limit int)) *MockRecipeRepository_ListFavourites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockRecipeRepository_ListFavourites_Call) Return(_a0 []*models.RecipeCard, _a1 int, _a2 error) *MockRecipeRepository_ListFavourites_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRecipeRepository_ListFavourites_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*models.RecipeCard, int, error)) *MockRecipeRepository_ListFavourites_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFavourite provides a mock function with given fields: ctx, userID, recipeID
func (_m *MockRecipeRepository) RemoveFavourite(ctx context.Context, userID string, recipeID string) error {
	ret := _m.Called(ctx, userID, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFavourite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, recipeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRecipeRepository_RemoveFavourite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFavourite'
type MockRecipeRepository_RemoveFavourite_Call struct {
	*mock.Call
}

// RemoveFavourite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - recipeID string
func (_e *MockRecipeRepository_Expecter) RemoveFavourite(ctx interface{}, userID interface{}, recipeID interface{}) *MockRecipeRepository_RemoveFavourite_Call {
	return &MockRecipeRepository_RemoveFavourite_Call{Call: _e.mock.On("RemoveFavourite", ctx, userID, recipeID)}
}

func (_c *MockRecipeRepository_RemoveFavourite_Call) Run(run func(ctx context.Context, userID string, recipeID string)) *MockRecipeRepository_RemoveFavourite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRecipeRepository_RemoveFavourite_Call) Return(_a0 error) *MockRecipeRepository_RemoveFavourite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRecipeRepository_RemoveFavourite_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRecipeRepository_RemoveFavourite_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecipeRepository creates a new instance of MockRecipeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecipeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecipeRepository {
	mock := &MockRecipeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
