// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"
)

// MockRecipeCategoryRepository is an autogenerated mock type for the RecipeCategoryRepository type
type MockRecipeCategoryRepository struct {
	mock.Mock
}

type MockRecipeCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecipeCategoryRepository) EXPECT() *MockRecipeCategoryRepository_Expecter {
	return &MockRecipeCategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name
func (_m *MockRecipeCategoryRepository) Create(ctx context.Context, name string) (*models.RecipeCategory, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.RecipeCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.RecipeCategory, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.RecipeCategory); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RecipeCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecipeCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRecipeCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRecipeCategoryRepository_Expecter) Create(ctx interface{}, name interface{}) *MockRecipeCategoryRepository_Create_Call {
	return &MockRecipeCategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, name)}
}

func (_c *MockRecipeCategoryRepository_Create_Call) Run(run func(ctx context.Context, name string)) *MockRecipeCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRecipeCategoryRepository_Create_Call) Return(_a0 *models.RecipeCategory, _a1 error) *MockRecipeCategoryRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecipeCategoryRepository_Create_Call) RunAndReturn(run func(context.Context, string) (*models.RecipeCategory, error)) *MockRecipeCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRecipeCategoryRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRecipeCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRecipeCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRecipeCategoryRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRecipeCategoryRepository_Delete_Call {
	return &MockRecipeCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRecipeCategoryRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRecipeCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRecipeCategoryRepository_Delete_Call) Return(_a0 error) *MockRecipeCategoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRecipeCategoryRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockRecipeCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockRecipeCategoryRepository) List(ctx context.Context) ([]*models.RecipeCategory, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.RecipeCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.RecipeCategory, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.RecipeCategory); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.RecipeCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecipeCategoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRecipeCategoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRecipeCategoryRepository_Expecter) List(ctx interface{}) *MockRecipeCategoryRepository_List_Call {
	return &MockRecipeCategoryRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRecipeCategoryRepository_List_Call) Run(run func(ctx context.Context)) *MockRecipeCategoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRecipeCategoryRepository_List_Call) Return(_a0 []*models.RecipeCategory, _a1 error) *MockRecipeCategoryRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecipeCategoryRepository_List_Call) RunAndReturn(run func(context.Context) ([]*models.RecipeCategory, error)) *MockRecipeCategoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name
func (_m *MockRecipeCategoryRepository) Update(ctx context.Context, id string, name string) (*models.RecipeCategory, error) {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.RecipeCategory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.RecipeCategory, error)); ok {
		return rf(ctx, id, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.RecipeCategory); ok {
		r0 = rf(ctx, id, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RecipeCategory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecipeCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRecipeCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
func (_e *MockRecipeCategoryRepository_Expecter) Update(ctx interface{}, id interface{}, name interface{}) *MockRecipeCategoryRepository_Update_Call {
	return &MockRecipeCategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, name)}
}

func (_c *MockRecipeCategoryRepository_Update_Call) Run(run func(ctx context.Context, id string, name string)) *MockRecipeCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRecipeCategoryRepository_Update_Call) Return(_a0 *models.RecipeCategory, _a1 error) *MockRecipeCategoryRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecipeCategoryRepository_Update_Call) RunAndReturn(run func(context.Context, string, string) (*models.RecipeCategory, error)) *MockRecipeCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecipeCategoryRepository creates a new instance of MockRecipeCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecipeCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecipeCategoryRepository {
	mock := &MockRecipeCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
