// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"

	time "time"
)

// MockPasswordResetTokenRepository is an autogenerated mock type for the PasswordResetTokenRepository type
type MockPasswordResetTokenRepository struct {
	mock.Mock
}

type MockPasswordResetTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordResetTokenRepository) EXPECT() *MockPasswordResetTokenRepository_Expecter {
	return &MockPasswordResetTokenRepository_Expecter{mock: &_m.Mock}
}

// AcquireUserLock provides a mock function with given fields: ctx, userID
func (_m *MockPasswordResetTokenRepository) AcquireUserLock(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AcquireUserLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetTokenRepository_AcquireUserLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireUserLock'
type MockPasswordResetTokenRepository_AcquireUserLock_Call struct {
	*mock.Call
}

// AcquireUserLock is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPasswordResetTokenRepository_Expecter) AcquireUserLock(ctx interface{}, userID interface{}) *MockPasswordResetTokenRepository_AcquireUserLock_Call {
	return &MockPasswordResetTokenRepository_AcquireUserLock_Call{Call: _e.mock.On("AcquireUserLock", ctx, userID)}
}

func (_c *MockPasswordResetTokenRepository_AcquireUserLock_Call) Run(run func(ctx context.Context, userID string)) *MockPasswordResetTokenRepository_AcquireUserLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordResetTokenRepository_AcquireUserLock_Call) Return(_a0 error) *MockPasswordResetTokenRepository_AcquireUserLock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetTokenRepository_AcquireUserLock_Call) RunAndReturn(run func(context.Context, string) error) *MockPasswordResetTokenRepository_AcquireUserLock_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userID, tokenHash, expiresAt
func (_m *MockPasswordResetTokenRepository) Create(ctx context.Context, userID string, tokenHash string, expiresAt time.Time) (*models.PasswordResetToken, error) {
	ret := _m.Called(ctx, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.PasswordResetToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*models.PasswordResetToken, error)); ok {
		return rf(ctx, userID, tokenHash, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *models.PasswordResetToken); ok {
		r0 = rf(ctx, userID, tokenHash, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasswordResetToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(ctx, userID, tokenHash, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordResetTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPasswordResetTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tokenHash string
//   - expiresAt time.Time
func (_e *MockPasswordResetTokenRepository_Expecter) Create(ctx interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *MockPasswordResetTokenRepository_Create_Call {
	return &MockPasswordResetTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, tokenHash, expiresAt)}
}

func (_c *MockPasswordResetTokenRepository_Create_Call) Run(run func(ctx context.Context, userID string, tokenHash string, expiresAt time.Time)) *MockPasswordResetTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockPasswordResetTokenRepository_Create_Call) Return(_a0 *models.PasswordResetToken, _a1 error) *MockPasswordResetTokenRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordResetTokenRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, time.Time) (*models.PasswordResetToken, error)) *MockPasswordResetTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteActiveForUser provides a mock function with given fields: ctx, userID
func (_m *MockPasswordResetTokenRepository) DeleteActiveForUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActiveForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetTokenRepository_DeleteActiveForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteActiveForUser'
type MockPasswordResetTokenRepository_DeleteActiveForUser_Call struct {
	*mock.Call
}

// DeleteActiveForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPasswordResetTokenRepository_Expecter) DeleteActiveForUser(ctx interface{}, userID interface{}) *MockPasswordResetTokenRepository_DeleteActiveForUser_Call {
	return &MockPasswordResetTokenRepository_DeleteActiveForUser_Call{Call: _e.mock.On("DeleteActiveForUser", ctx, userID)}
}

func (_c *MockPasswordResetTokenRepository_DeleteActiveForUser_Call) Run(run func(ctx context.Context, userID string)) *MockPasswordResetTokenRepository_DeleteActiveForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordResetTokenRepository_DeleteActiveForUser_Call) Return(_a0 error) *MockPasswordResetTokenRepository_DeleteActiveForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetTokenRepository_DeleteActiveForUser_Call) RunAndReturn(run func(context.Context, string) error) *MockPasswordResetTokenRepository_DeleteActiveForUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockPasswordResetTokenRepository) FindActiveByTokenHash(ctx context.Context, tokenHash string) (*models.PasswordResetToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByTokenHash")
	}

	var r0 *models.PasswordResetToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PasswordResetToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PasswordResetToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasswordResetToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordResetTokenRepository_FindActiveByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByTokenHash'
type MockPasswordResetTokenRepository_FindActiveByTokenHash_Call struct {
	*mock.Call
}

// FindActiveByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockPasswordResetTokenRepository_Expecter) FindActiveByTokenHash(ctx interface{}, tokenHash interface{}) *MockPasswordResetTokenRepository_FindActiveByTokenHash_Call {
	return &MockPasswordResetTokenRepository_FindActiveByTokenHash_Call{Call: _e.mock.On("FindActiveByTokenHash", ctx, tokenHash)}
}

func (_c *MockPasswordResetTokenRepository_FindActiveByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockPasswordResetTokenRepository_FindActiveByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordResetTokenRepository_FindActiveByTokenHash_Call) Return(_a0 *models.PasswordResetToken, _a1 error) *MockPasswordResetTokenRepository_FindActiveByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordResetTokenRepository_FindActiveByTokenHash_Call) RunAndReturn(run func(context.Context, string) (*models.PasswordResetToken, error)) *MockPasswordResetTokenRepository_FindActiveByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByUserID provides a mock function with given fields: ctx, userID
func (_m *MockPasswordResetTokenRepository) FindActiveByUserID(ctx context.Context, userID string) (*models.PasswordResetToken, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByUserID")
	}

	var r0 *models.PasswordResetToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PasswordResetToken, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PasswordResetToken); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasswordResetToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordResetTokenRepository_FindActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByUserID'
type MockPasswordResetTokenRepository_FindActiveByUserID_Call struct {
	*mock.Call
}

// FindActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPasswordResetTokenRepository_Expecter) FindActiveByUserID(ctx interface{}, userID interface{}) *MockPasswordResetTokenRepository_FindActiveByUserID_Call {
	return &MockPasswordResetTokenRepository_FindActiveByUserID_Call{Call: _e.mock.On("FindActiveByUserID", ctx, userID)}
}

func (_c *MockPasswordResetTokenRepository_FindActiveByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockPasswordResetTokenRepository_FindActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordResetTokenRepository_FindActiveByUserID_Call) Return(_a0 *models.PasswordResetToken, _a1 error) *MockPasswordResetTokenRepository_FindActiveByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordResetTokenRepository_FindActiveByUserID_Call) RunAndReturn(run func(context.Context, string) (*models.PasswordResetToken, error)) *MockPasswordResetTokenRepository_FindActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function with given fields: ctx, id
func (_m *MockPasswordResetTokenRepository) MarkUsed(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordResetTokenRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockPasswordResetTokenRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPasswordResetTokenRepository_Expecter) MarkUsed(ctx interface{}, id interface{}) *MockPasswordResetTokenRepository_MarkUsed_Call {
	return &MockPasswordResetTokenRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, id)}
}

func (_c *MockPasswordResetTokenRepository_MarkUsed_Call) Run(run func(ctx context.Context, id string)) *MockPasswordResetTokenRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordResetTokenRepository_MarkUsed_Call) Return(_a0 bool, _a1 error) *MockPasswordResetTokenRepository_MarkUsed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordResetTokenRepository_MarkUsed_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockPasswordResetTokenRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordResetTokenRepository creates a new instance of MockPasswordResetTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordResetTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordResetTokenRepository {
	mock := &MockPasswordResetTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
