// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"
)

// MockRegularRepository is an autogenerated mock type for the RegularRepository type
type MockRegularRepository struct {
	mock.Mock
}

type MockRegularRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegularRepository) EXPECT() *MockRegularRepository_Expecter {
	return &MockRegularRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, itemID, unitID, quantity, limit
func (_m *MockRegularRepository) Create(ctx context.Context, userID string, itemID string, unitID *string, quantity float64, limit int) (*models.Regular, error) {
	ret := _m.Called(ctx, userID, itemID, unitID, quantity, limit)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Regular
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, float64, int) (*models.Regular, error)); ok {
		return rf(ctx, userID, itemID, unitID, quantity, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, float64, int) *models.Regular); ok {
		r0 = rf(ctx, userID, itemID, unitID, quantity, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Regular)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *string, float64, int) error); ok {
		r1 = rf(ctx, userID, itemID, unitID, quantity, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegularRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRegularRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - itemID string
//   - unitID *string
//   - quantity float64
//   - limit int
func (_e *MockRegularRepository_Expecter) Create(ctx interface{}, userID interface{}, itemID interface{}, unitID interface{}, quantity interface{}, limit interface{}) *MockRegularRepository_Create_Call {
	return &MockRegularRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, itemID, unitID, quantity, limit)}
}

func (_c *MockRegularRepository_Create_Call) Run(run func(ctx context.Context, userID string, itemID string, unitID *string, quantity float64, limit int)) *MockRegularRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string), args[4].(float64), args[5].(int))
	})
	return _c
}

func (_c *MockRegularRepository_Create_Call) Return(_a0 *models.Regular, _a1 error) *MockRegularRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegularRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, *string, float64, int) (*models.Regular, error)) *MockRegularRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, regularID
func (_m *MockRegularRepository) Delete(ctx context.Context, userID string, regularID string) error {
	ret := _m.Called(ctx, userID, regularID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, regularID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegularRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRegularRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - regularID string
func (_e *MockRegularRepository_Expecter) Delete(ctx interface{}, userID interface{}, regularID interface{}) *MockRegularRepository_Delete_Call {
	return &MockRegularRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, regularID)}
}

func (_c *MockRegularRepository_Delete_Call) Run(run func(ctx context.Context, userID string, regularID string)) *MockRegularRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRegularRepository_Delete_Call) Return(_a0 error) *MockRegularRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegularRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRegularRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID
func (_m *MockRegularRepository) List(ctx context.Context, userID string) ([]models.Regular, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Regular
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Regular, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Regular); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Regular)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegularRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRegularRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRegularRepository_Expecter) List(ctx interface{}, userID interface{}) *MockRegularRepository_List_Call {
	return &MockRegularRepository_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockRegularRepository_List_Call) Run(run func(ctx context.Context, userID string)) *MockRegularRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegularRepository_List_Call) Return(_a0 []models.Regular, _a1 error) *MockRegularRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegularRepository_List_Call) RunAndReturn(run func(context.Context, string) ([]models.Regular, error)) *MockRegularRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, regularID, unitID, quantity
func (_m *MockRegularRepository) Update(ctx context.Context, userID string, regularID string, unitID *string, quantity float64) (*models.Regular, error) {
	ret := _m.Called(ctx, userID, regularID, unitID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Regular
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, float64) (*models.Regular, error)); ok {
		return rf(ctx, userID, regularID, unitID, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string, float64) *models.Regular); ok {
		r0 = rf(ctx, userID, regularID, unitID, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Regular)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *string, float64) error); ok {
		r1 = rf(ctx, userID, regularID, unitID, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegularRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRegularRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - regularID string
//   - unitID *string
//   - quantity float64
func (_e *MockRegularRepository_Expecter) Update(ctx interface{}, userID interface{}, regularID interface{}, unitID interface{}, quantity interface{}) *MockRegularRepository_Update_Call {
	return &MockRegularRepository_Update_Call{Call: _e.mock.On("Update", ctx, userID, regularID, unitID, quantity)}
}

func (_c *MockRegularRepository_Update_Call) Run(run func(ctx context.Context, userID string, regularID string, unitID *string, quantity float64)) *MockRegularRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string), args[4].(float64))
	})
	return _c
}

func (_c *MockRegularRepository_Update_Call) Return(_a0 *models.Regular, _a1 error) *MockRegularRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegularRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, *string, float64) (*models.Regular, error)) *MockRegularRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegularRepository creates a new instance of MockRegularRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegularRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegularRepository {
	mock := &MockRegularRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
