// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountRecipeRepository is an autogenerated mock type for the AccountRecipeRepository type
type MockAccountRecipeRepository struct {
	mock.Mock
}

type MockAccountRecipeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRecipeRepository) EXPECT() *MockAccountRecipeRepository_Expecter {
	return &MockAccountRecipeRepository_Expecter{mock: &_m.Mock}
}

// DeleteUnapprovedByCreator provides a mock function with given fields: ctx, creatorID
func (_m *MockAccountRecipeRepository) DeleteUnapprovedByCreator(ctx context.Context, creatorID string) ([]string, []string, error) {
	ret := _m.Called(ctx, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUnapprovedByCreator")
	}

	var r0 []string
	var r1 []string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, []string, error)); ok {
		return rf(ctx, creatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) []string); ok {
		r1 = rf(ctx, creatorID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, creatorID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAccountRecipeRepository_DeleteUnapprovedByCreator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUnapprovedByCreator'
type MockAccountRecipeRepository_DeleteUnapprovedByCreator_Call struct {
	*mock.Call
}

// DeleteUnapprovedByCreator is a helper method to define mock.On call
//   - ctx context.Context
//   - creatorID string
func (_e *MockAccountRecipeRepository_Expecter) DeleteUnapprovedByCreator(ctx interface{}, creatorID interface{}) *MockAccountRecipeRepository_DeleteUnapprovedByCreator_Call {
	return &MockAccountRecipeRepository_DeleteUnapprovedByCreator_Call{Call: _e.mock.On("DeleteUnapprovedByCreator", ctx, creatorID)}
}

func (_c *MockAccountRecipeRepository_DeleteUnapprovedByCreator_Call) Run(run func(ctx context.Context, creatorID string)) *MockAccountRecipeRepository_DeleteUnapprovedByCreator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountRecipeRepository_DeleteUnapprovedByCreator_Call) Return(menuUserIDs []string, orphanedImages []string, err error) *MockAccountRecipeRepository_DeleteUnapprovedByCreator_Call {
	_c.Call.Return(menuUserIDs, orphanedImages, err)
	return _c
}

func (_c *MockAccountRecipeRepository_DeleteUnapprovedByCreator_Call) RunAndReturn(run func(context.Context, string) ([]string, []string, error)) *MockAccountRecipeRepository_DeleteUnapprovedByCreator_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountRecipeRepository creates a new instance of MockAccountRecipeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRecipeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRecipeRepository {
	mock := &MockAccountRecipeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
