// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	cloudinary "github.com/franciskershaw/crockpot-go/internal/cloudinary"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockImageStore is an autogenerated mock type for the ImageStore type
type MockImageStore struct {
	mock.Mock
}

type MockImageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageStore) EXPECT() *MockImageStore_Expecter {
	return &MockImageStore_Expecter{mock: &_m.Mock}
}

// Destroy provides a mock function with given fields: ctx, publicID
func (_m *MockImageStore) Destroy(ctx context.Context, publicID string) error {
	ret := _m.Called(ctx, publicID)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, publicID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockImageStore_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockImageStore_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
//   - publicID string
func (_e *MockImageStore_Expecter) Destroy(ctx interface{}, publicID interface{}) *MockImageStore_Destroy_Call {
	return &MockImageStore_Destroy_Call{Call: _e.mock.On("Destroy", ctx, publicID)}
}

func (_c *MockImageStore_Destroy_Call) Run(run func(ctx context.Context, publicID string)) *MockImageStore_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockImageStore_Destroy_Call) Return(_a0 error) *MockImageStore_Destroy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageStore_Destroy_Call) RunAndReturn(run func(context.Context, string) error) *MockImageStore_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, file, publicID
func (_m *MockImageStore) Upload(ctx context.Context, file io.Reader, publicID string) (cloudinary.UploadedImage, error) {
	ret := _m.Called(ctx, file, publicID)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 cloudinary.UploadedImage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string) (cloudinary.UploadedImage, error)); ok {
		return rf(ctx, file, publicID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string) cloudinary.UploadedImage); ok {
		r0 = rf(ctx, file, publicID)
	} else {
		r0 = ret.Get(0).(cloudinary.UploadedImage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string) error); ok {
		r1 = rf(ctx, file, publicID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageStore_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockImageStore_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
//   - publicID string
func (_e *MockImageStore_Expecter) Upload(ctx interface{}, file interface{}, publicID interface{}) *MockImageStore_Upload_Call {
	return &MockImageStore_Upload_Call{Call: _e.mock.On("Upload", ctx, file, publicID)}
}

func (_c *MockImageStore_Upload_Call) Run(run func(ctx context.Context, file io.Reader, publicID string)) *MockImageStore_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader), args[2].(string))
	})
	return _c
}

func (_c *MockImageStore_Upload_Call) Return(_a0 cloudinary.UploadedImage, _a1 error) *MockImageStore_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageStore_Upload_Call) RunAndReturn(run func(context.Context, io.Reader, string) (cloudinary.UploadedImage, error)) *MockImageStore_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageStore creates a new instance of MockImageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageStore {
	mock := &MockImageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
