// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"
)

// MockUnitRepository is an autogenerated mock type for the UnitRepository type
type MockUnitRepository struct {
	mock.Mock
}

type MockUnitRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitRepository) EXPECT() *MockUnitRepository_Expecter {
	return &MockUnitRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name, abbreviation
func (_m *MockUnitRepository) Create(ctx context.Context, name string, abbreviation string) (*models.Unit, error) {
	ret := _m.Called(ctx, name, abbreviation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Unit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Unit, error)); ok {
		return rf(ctx, name, abbreviation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Unit); ok {
		r0 = rf(ctx, name, abbreviation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Unit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, abbreviation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUnitRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUnitRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - abbreviation string
func (_e *MockUnitRepository_Expecter) Create(ctx interface{}, name interface{}, abbreviation interface{}) *MockUnitRepository_Create_Call {
	return &MockUnitRepository_Create_Call{Call: _e.mock.On("Create", ctx, name, abbreviation)}
}

func (_c *MockUnitRepository_Create_Call) Run(run func(ctx context.Context, name string, abbreviation string)) *MockUnitRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUnitRepository_Create_Call) Return(_a0 *models.Unit, _a1 error) *MockUnitRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUnitRepository_Create_Call) RunAndReturn(run func(context.Context, string, string) (*models.Unit, error)) *MockUnitRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUnitRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnitRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUnitRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUnitRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockUnitRepository_Delete_Call {
	return &MockUnitRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUnitRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockUnitRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUnitRepository_Delete_Call) Return(_a0 error) *MockUnitRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockUnitRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockUnitRepository) List(ctx context.Context) ([]*models.Unit, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Unit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Unit, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Unit); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Unit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUnitRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUnitRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitRepository_Expecter) List(ctx interface{}) *MockUnitRepository_List_Call {
	return &MockUnitRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockUnitRepository_List_Call) Run(run func(ctx context.Context)) *MockUnitRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUnitRepository_List_Call) Return(_a0 []*models.Unit, _a1 error) *MockUnitRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUnitRepository_List_Call) RunAndReturn(run func(context.Context) ([]*models.Unit, error)) *MockUnitRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name, abbreviation
func (_m *MockUnitRepository) Update(ctx context.Context, id string, name string, abbreviation string) (*models.Unit, error) {
	ret := _m.Called(ctx, id, name, abbreviation)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Unit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.Unit, error)); ok {
		return rf(ctx, id, name, abbreviation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.Unit); ok {
		r0 = rf(ctx, id, name, abbreviation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Unit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, id, name, abbreviation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUnitRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUnitRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
//   - abbreviation string
func (_e *MockUnitRepository_Expecter) Update(ctx interface{}, id interface{}, name interface{}, abbreviation interface{}) *MockUnitRepository_Update_Call {
	return &MockUnitRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, name, abbreviation)}
}

func (_c *MockUnitRepository_Update_Call) Run(run func(ctx context.Context, id string, name string, abbreviation string)) *MockUnitRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUnitRepository_Update_Call) Return(_a0 *models.Unit, _a1 error) *MockUnitRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUnitRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.Unit, error)) *MockUnitRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnitRepository creates a new instance of MockUnitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitRepository {
	mock := &MockUnitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
