// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"
)

// MockRecipeRepository is an autogenerated mock type for the RecipeRepository type
type MockRecipeRepository struct {
	mock.Mock
}

type MockRecipeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecipeRepository) EXPECT() *MockRecipeRepository_Expecter {
	return &MockRecipeRepository_Expecter{mock: &_m.Mock}
}

// CountByCreator provides a mock function with given fields: ctx, userID
func (_m *MockRecipeRepository) CountByCreator(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountByCreator")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecipeRepository_CountByCreator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByCreator'
type MockRecipeRepository_CountByCreator_Call struct {
	*mock.Call
}

// CountByCreator is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRecipeRepository_Expecter) CountByCreator(ctx interface{}, userID interface{}) *MockRecipeRepository_CountByCreator_Call {
	return &MockRecipeRepository_CountByCreator_Call{Call: _e.mock.On("CountByCreator", ctx, userID)}
}

func (_c *MockRecipeRepository_CountByCreator_Call) Run(run func(ctx context.Context, userID string)) *MockRecipeRepository_CountByCreator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRecipeRepository_CountByCreator_Call) Return(_a0 int, _a1 error) *MockRecipeRepository_CountByCreator_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecipeRepository_CountByCreator_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockRecipeRepository_CountByCreator_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, input
func (_m *MockRecipeRepository) Create(ctx context.Context, input models.CreateRecipeInput) (*models.Recipe, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Recipe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateRecipeInput) (*models.Recipe, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateRecipeInput) *models.Recipe); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Recipe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateRecipeInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRecipeRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRecipeRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateRecipeInput
func (_e *MockRecipeRepository_Expecter) Create(ctx interface{}, input interface{}) *MockRecipeRepository_Create_Call {
	return &MockRecipeRepository_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockRecipeRepository_Create_Call) Run(run func(ctx context.Context, input models.CreateRecipeInput)) *MockRecipeRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateRecipeInput))
	})
	return _c
}

func (_c *MockRecipeRepository_Create_Call) Return(_a0 *models.Recipe, _a1 error) *MockRecipeRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRecipeRepository_Create_Call) RunAndReturn(run func(context.Context, models.CreateRecipeInput) (*models.Recipe, error)) *MockRecipeRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRecipeRepository creates a new instance of MockRecipeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecipeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecipeRepository {
	mock := &MockRecipeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
