// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"
)

// MockItemRepository is an autogenerated mock type for the ItemRepository type
type MockItemRepository struct {
	mock.Mock
}

type MockItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemRepository) EXPECT() *MockItemRepository_Expecter {
	return &MockItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, name, categoryID, unitIDs
func (_m *MockItemRepository) Create(ctx context.Context, name string, categoryID string, unitIDs []string) (*models.Item, error) {
	ret := _m.Called(ctx, name, categoryID, unitIDs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) (*models.Item, error)); ok {
		return rf(ctx, name, categoryID, unitIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) *models.Item); ok {
		r0 = rf(ctx, name, categoryID, unitIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = rf(ctx, name, categoryID, unitIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - categoryID string
//   - unitIDs []string
func (_e *MockItemRepository_Expecter) Create(ctx interface{}, name interface{}, categoryID interface{}, unitIDs interface{}) *MockItemRepository_Create_Call {
	return &MockItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, name, categoryID, unitIDs)}
}

func (_c *MockItemRepository_Create_Call) Run(run func(ctx context.Context, name string, categoryID string, unitIDs []string)) *MockItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockItemRepository_Create_Call) Return(_a0 *models.Item, _a1 error) *MockItemRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, []string) (*models.Item, error)) *MockItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockItemRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockItemRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockItemRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockItemRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockItemRepository_Delete_Call {
	return &MockItemRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockItemRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockItemRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockItemRepository_Delete_Call) Return(_a0 error) *MockItemRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockItemRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockItemRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockItemRepository) List(ctx context.Context) ([]*models.Item, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Item, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Item); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockItemRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockItemRepository_Expecter) List(ctx interface{}) *MockItemRepository_List_Call {
	return &MockItemRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockItemRepository_List_Call) Run(run func(ctx context.Context)) *MockItemRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockItemRepository_List_Call) Return(_a0 []*models.Item, _a1 error) *MockItemRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_List_Call) RunAndReturn(run func(context.Context) ([]*models.Item, error)) *MockItemRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name, categoryID, unitIDs
func (_m *MockItemRepository) Update(ctx context.Context, id string, name string, categoryID string, unitIDs []string) (*models.Item, error) {
	ret := _m.Called(ctx, id, name, categoryID, unitIDs)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) (*models.Item, error)); ok {
		return rf(ctx, id, name, categoryID, unitIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []string) *models.Item); ok {
		r0 = rf(ctx, id, name, categoryID, unitIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []string) error); ok {
		r1 = rf(ctx, id, name, categoryID, unitIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockItemRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
//   - categoryID string
//   - unitIDs []string
func (_e *MockItemRepository_Expecter) Update(ctx interface{}, id interface{}, name interface{}, categoryID interface{}, unitIDs interface{}) *MockItemRepository_Update_Call {
	return &MockItemRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, name, categoryID, unitIDs)}
}

func (_c *MockItemRepository_Update_Call) Run(run func(ctx context.Context, id string, name string, categoryID string, unitIDs []string)) *MockItemRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]string))
	})
	return _c
}

func (_c *MockItemRepository_Update_Call) Return(_a0 *models.Item, _a1 error) *MockItemRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, string, []string) (*models.Item, error)) *MockItemRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemRepository creates a new instance of MockItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemRepository {
	mock := &MockItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
