// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockShoppingListRegenerator is an autogenerated mock type for the ShoppingListRegenerator type
type MockShoppingListRegenerator struct {
	mock.Mock
}

type MockShoppingListRegenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShoppingListRegenerator) EXPECT() *MockShoppingListRegenerator_Expecter {
	return &MockShoppingListRegenerator_Expecter{mock: &_m.Mock}
}

// Regenerate provides a mock function with given fields: ctx, userID
func (_m *MockShoppingListRegenerator) Regenerate(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Regenerate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockShoppingListRegenerator_Regenerate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Regenerate'
type MockShoppingListRegenerator_Regenerate_Call struct {
	*mock.Call
}

// Regenerate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockShoppingListRegenerator_Expecter) Regenerate(ctx interface{}, userID interface{}) *MockShoppingListRegenerator_Regenerate_Call {
	return &MockShoppingListRegenerator_Regenerate_Call{Call: _e.mock.On("Regenerate", ctx, userID)}
}

func (_c *MockShoppingListRegenerator_Regenerate_Call) Run(run func(ctx context.Context, userID string)) *MockShoppingListRegenerator_Regenerate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockShoppingListRegenerator_Regenerate_Call) Return(_a0 error) *MockShoppingListRegenerator_Regenerate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShoppingListRegenerator_Regenerate_Call) RunAndReturn(run func(context.Context, string) error) *MockShoppingListRegenerator_Regenerate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShoppingListRegenerator creates a new instance of MockShoppingListRegenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShoppingListRegenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShoppingListRegenerator {
	mock := &MockShoppingListRegenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
