// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"

	time "time"
)

// MockEmailVerificationTokenRepository is an autogenerated mock type for the EmailVerificationTokenRepository type
type MockEmailVerificationTokenRepository struct {
	mock.Mock
}

type MockEmailVerificationTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailVerificationTokenRepository) EXPECT() *MockEmailVerificationTokenRepository_Expecter {
	return &MockEmailVerificationTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, tokenHash, expiresAt
func (_m *MockEmailVerificationTokenRepository) Create(ctx context.Context, userID string, tokenHash string, expiresAt time.Time) (*models.EmailVerificationToken, error) {
	ret := _m.Called(ctx, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.EmailVerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*models.EmailVerificationToken, error)); ok {
		return rf(ctx, userID, tokenHash, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *models.EmailVerificationToken); ok {
		r0 = rf(ctx, userID, tokenHash, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailVerificationToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(ctx, userID, tokenHash, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmailVerificationTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEmailVerificationTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tokenHash string
//   - expiresAt time.Time
func (_e *MockEmailVerificationTokenRepository_Expecter) Create(ctx interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *MockEmailVerificationTokenRepository_Create_Call {
	return &MockEmailVerificationTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, tokenHash, expiresAt)}
}

func (_c *MockEmailVerificationTokenRepository_Create_Call) Run(run func(ctx context.Context, userID string, tokenHash string, expiresAt time.Time)) *MockEmailVerificationTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockEmailVerificationTokenRepository_Create_Call) Return(_a0 *models.EmailVerificationToken, _a1 error) *MockEmailVerificationTokenRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmailVerificationTokenRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, time.Time) (*models.EmailVerificationToken, error)) *MockEmailVerificationTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteActiveForUser provides a mock function with given fields: ctx, userID
func (_m *MockEmailVerificationTokenRepository) DeleteActiveForUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActiveForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailVerificationTokenRepository_DeleteActiveForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteActiveForUser'
type MockEmailVerificationTokenRepository_DeleteActiveForUser_Call struct {
	*mock.Call
}

// DeleteActiveForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockEmailVerificationTokenRepository_Expecter) DeleteActiveForUser(ctx interface{}, userID interface{}) *MockEmailVerificationTokenRepository_DeleteActiveForUser_Call {
	return &MockEmailVerificationTokenRepository_DeleteActiveForUser_Call{Call: _e.mock.On("DeleteActiveForUser", ctx, userID)}
}

func (_c *MockEmailVerificationTokenRepository_DeleteActiveForUser_Call) Run(run func(ctx context.Context, userID string)) *MockEmailVerificationTokenRepository_DeleteActiveForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEmailVerificationTokenRepository_DeleteActiveForUser_Call) Return(_a0 error) *MockEmailVerificationTokenRepository_DeleteActiveForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailVerificationTokenRepository_DeleteActiveForUser_Call) RunAndReturn(run func(context.Context, string) error) *MockEmailVerificationTokenRepository_DeleteActiveForUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByUserID provides a mock function with given fields: ctx, userID
func (_m *MockEmailVerificationTokenRepository) FindActiveByUserID(ctx context.Context, userID string) (*models.EmailVerificationToken, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByUserID")
	}

	var r0 *models.EmailVerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.EmailVerificationToken, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.EmailVerificationToken); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailVerificationToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmailVerificationTokenRepository_FindActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByUserID'
type MockEmailVerificationTokenRepository_FindActiveByUserID_Call struct {
	*mock.Call
}

// FindActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockEmailVerificationTokenRepository_Expecter) FindActiveByUserID(ctx interface{}, userID interface{}) *MockEmailVerificationTokenRepository_FindActiveByUserID_Call {
	return &MockEmailVerificationTokenRepository_FindActiveByUserID_Call{Call: _e.mock.On("FindActiveByUserID", ctx, userID)}
}

func (_c *MockEmailVerificationTokenRepository_FindActiveByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockEmailVerificationTokenRepository_FindActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEmailVerificationTokenRepository_FindActiveByUserID_Call) Return(_a0 *models.EmailVerificationToken, _a1 error) *MockEmailVerificationTokenRepository_FindActiveByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmailVerificationTokenRepository_FindActiveByUserID_Call) RunAndReturn(run func(context.Context, string) (*models.EmailVerificationToken, error)) *MockEmailVerificationTokenRepository_FindActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementAttempts provides a mock function with given fields: ctx, id
func (_m *MockEmailVerificationTokenRepository) IncrementAttempts(ctx context.Context, id string) (*models.EmailVerificationToken, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementAttempts")
	}

	var r0 *models.EmailVerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.EmailVerificationToken, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.EmailVerificationToken); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailVerificationToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmailVerificationTokenRepository_IncrementAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementAttempts'
type MockEmailVerificationTokenRepository_IncrementAttempts_Call struct {
	*mock.Call
}

// IncrementAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEmailVerificationTokenRepository_Expecter) IncrementAttempts(ctx interface{}, id interface{}) *MockEmailVerificationTokenRepository_IncrementAttempts_Call {
	return &MockEmailVerificationTokenRepository_IncrementAttempts_Call{Call: _e.mock.On("IncrementAttempts", ctx, id)}
}

func (_c *MockEmailVerificationTokenRepository_IncrementAttempts_Call) Run(run func(ctx context.Context, id string)) *MockEmailVerificationTokenRepository_IncrementAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEmailVerificationTokenRepository_IncrementAttempts_Call) Return(_a0 *models.EmailVerificationToken, _a1 error) *MockEmailVerificationTokenRepository_IncrementAttempts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmailVerificationTokenRepository_IncrementAttempts_Call) RunAndReturn(run func(context.Context, string) (*models.EmailVerificationToken, error)) *MockEmailVerificationTokenRepository_IncrementAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function with given fields: ctx, id
func (_m *MockEmailVerificationTokenRepository) MarkUsed(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailVerificationTokenRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockEmailVerificationTokenRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockEmailVerificationTokenRepository_Expecter) MarkUsed(ctx interface{}, id interface{}) *MockEmailVerificationTokenRepository_MarkUsed_Call {
	return &MockEmailVerificationTokenRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, id)}
}

func (_c *MockEmailVerificationTokenRepository_MarkUsed_Call) Run(run func(ctx context.Context, id string)) *MockEmailVerificationTokenRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEmailVerificationTokenRepository_MarkUsed_Call) Return(_a0 error) *MockEmailVerificationTokenRepository_MarkUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailVerificationTokenRepository_MarkUsed_Call) RunAndReturn(run func(context.Context, string) error) *MockEmailVerificationTokenRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailVerificationTokenRepository creates a new instance of MockEmailVerificationTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailVerificationTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailVerificationTokenRepository {
	mock := &MockEmailVerificationTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
