// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/franciskershaw/crockpot-go/internal/models"

	time "time"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// CreateFamily provides a mock function with given fields: ctx, id, userID, tokenHash, expiresAt
func (_m *MockRefreshTokenRepository) CreateFamily(ctx context.Context, id string, userID string, tokenHash string, expiresAt time.Time) (*models.RefreshTokenFamily, error) {
	ret := _m.Called(ctx, id, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateFamily")
	}

	var r0 *models.RefreshTokenFamily
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) (*models.RefreshTokenFamily, error)); ok {
		return rf(ctx, id, userID, tokenHash, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) *models.RefreshTokenFamily); ok {
		r0 = rf(ctx, id, userID, tokenHash, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshTokenFamily)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, time.Time) error); ok {
		r1 = rf(ctx, id, userID, tokenHash, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_CreateFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFamily'
type MockRefreshTokenRepository_CreateFamily_Call struct {
	*mock.Call
}

// CreateFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
//   - tokenHash string
//   - expiresAt time.Time
func (_e *MockRefreshTokenRepository_Expecter) CreateFamily(ctx interface{}, id interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *MockRefreshTokenRepository_CreateFamily_Call {
	return &MockRefreshTokenRepository_CreateFamily_Call{Call: _e.mock.On("CreateFamily", ctx, id, userID, tokenHash, expiresAt)}
}

func (_c *MockRefreshTokenRepository_CreateFamily_Call) Run(run func(ctx context.Context, id string, userID string, tokenHash string, expiresAt time.Time)) *MockRefreshTokenRepository_CreateFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(time.Time))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_CreateFamily_Call) Return(_a0 *models.RefreshTokenFamily, _a1 error) *MockRefreshTokenRepository_CreateFamily_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_CreateFamily_Call) RunAndReturn(run func(context.Context, string, string, string, time.Time) (*models.RefreshTokenFamily, error)) *MockRefreshTokenRepository_CreateFamily_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStaleFamiliesForUser provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) DeleteStaleFamiliesForUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStaleFamiliesForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStaleFamiliesForUser'
type MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call struct {
	*mock.Call
}

// DeleteStaleFamiliesForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRefreshTokenRepository_Expecter) DeleteStaleFamiliesForUser(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call {
	return &MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call{Call: _e.mock.On("DeleteStaleFamiliesForUser", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call) Run(run func(ctx context.Context, userID string)) *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call) Return(_a0 error) *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call) RunAndReturn(run func(context.Context, string) error) *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindFamilyByID provides a mock function with given fields: ctx, id, userID
func (_m *MockRefreshTokenRepository) FindFamilyByID(ctx context.Context, id string, userID string) (*models.RefreshTokenFamily, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindFamilyByID")
	}

	var r0 *models.RefreshTokenFamily
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.RefreshTokenFamily, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.RefreshTokenFamily); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshTokenFamily)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_FindFamilyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindFamilyByID'
type MockRefreshTokenRepository_FindFamilyByID_Call struct {
	*mock.Call
}

// FindFamilyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockRefreshTokenRepository_Expecter) FindFamilyByID(ctx interface{}, id interface{}, userID interface{}) *MockRefreshTokenRepository_FindFamilyByID_Call {
	return &MockRefreshTokenRepository_FindFamilyByID_Call{Call: _e.mock.On("FindFamilyByID", ctx, id, userID)}
}

func (_c *MockRefreshTokenRepository_FindFamilyByID_Call) Run(run func(ctx context.Context, id string, userID string)) *MockRefreshTokenRepository_FindFamilyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindFamilyByID_Call) Return(_a0 *models.RefreshTokenFamily, _a1 error) *MockRefreshTokenRepository_FindFamilyByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_FindFamilyByID_Call) RunAndReturn(run func(context.Context, string, string) (*models.RefreshTokenFamily, error)) *MockRefreshTokenRepository_FindFamilyByID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllFamiliesForUser provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) RevokeAllFamiliesForUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllFamiliesForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeAllFamiliesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllFamiliesForUser'
type MockRefreshTokenRepository_RevokeAllFamiliesForUser_Call struct {
	*mock.Call
}

// RevokeAllFamiliesForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRefreshTokenRepository_Expecter) RevokeAllFamiliesForUser(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_RevokeAllFamiliesForUser_Call {
	return &MockRefreshTokenRepository_RevokeAllFamiliesForUser_Call{Call: _e.mock.On("RevokeAllFamiliesForUser", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_RevokeAllFamiliesForUser_Call) Run(run func(ctx context.Context, userID string)) *MockRefreshTokenRepository_RevokeAllFamiliesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllFamiliesForUser_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeAllFamiliesForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllFamiliesForUser_Call) RunAndReturn(run func(context.Context, string) error) *MockRefreshTokenRepository_RevokeAllFamiliesForUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeFamily provides a mock function with given fields: ctx, familyID
func (_m *MockRefreshTokenRepository) RevokeFamily(ctx context.Context, familyID string) error {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeFamily")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, familyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeFamily'
type MockRefreshTokenRepository_RevokeFamily_Call struct {
	*mock.Call
}

// RevokeFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID string
func (_e *MockRefreshTokenRepository_Expecter) RevokeFamily(ctx interface{}, familyID interface{}) *MockRefreshTokenRepository_RevokeFamily_Call {
	return &MockRefreshTokenRepository_RevokeFamily_Call{Call: _e.mock.On("RevokeFamily", ctx, familyID)}
}

func (_c *MockRefreshTokenRepository_RevokeFamily_Call) Run(run func(ctx context.Context, familyID string)) *MockRefreshTokenRepository_RevokeFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeFamily_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeFamily_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeFamily_Call) RunAndReturn(run func(context.Context, string) error) *MockRefreshTokenRepository_RevokeFamily_Call {
	_c.Call.Return(run)
	return _c
}

// RotateFamily provides a mock function with given fields: ctx, familyID, newTokenHash, newExpiresAt
func (_m *MockRefreshTokenRepository) RotateFamily(ctx context.Context, familyID string, newTokenHash string, newExpiresAt time.Time) error {
	ret := _m.Called(ctx, familyID, newTokenHash, newExpiresAt)

	if len(ret) == 0 {
		panic("no return value specified for RotateFamily")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, familyID, newTokenHash, newExpiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RotateFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateFamily'
type MockRefreshTokenRepository_RotateFamily_Call struct {
	*mock.Call
}

// RotateFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID string
//   - newTokenHash string
//   - newExpiresAt time.Time
func (_e *MockRefreshTokenRepository_Expecter) RotateFamily(ctx interface{}, familyID interface{}, newTokenHash interface{}, newExpiresAt interface{}) *MockRefreshTokenRepository_RotateFamily_Call {
	return &MockRefreshTokenRepository_RotateFamily_Call{Call: _e.mock.On("RotateFamily", ctx, familyID, newTokenHash, newExpiresAt)}
}

func (_c *MockRefreshTokenRepository_RotateFamily_Call) Run(run func(ctx context.Context, familyID string, newTokenHash string, newExpiresAt time.Time)) *MockRefreshTokenRepository_RotateFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RotateFamily_Call) Return(_a0 error) *MockRefreshTokenRepository_RotateFamily_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RotateFamily_Call) RunAndReturn(run func(context.Context, string, string, time.Time) error) *MockRefreshTokenRepository_RotateFamily_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
