with-expecter: true
inpackage: false
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/franciskershaw/crockpot-go/internal/handler:
    interfaces:
      UserRepository:
      OAuthManager:
      RefreshTokenRepository:
      EmailVerificationTokenRepository:
      PasswordResetTokenRepository:
      EmailSender:
      Transactor:
      ItemCategoryRepository:
