// Code generated by mockery. DO NOT EDIT.

package handler

import (
	context "context"

	models "github.com/franciskershaw/crockpot-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUnconfirmedUser provides a mock function with given fields: ctx, email, passwordHash, name
func (_m *MockUserRepository) CreateUnconfirmedUser(ctx context.Context, email string, passwordHash string, name string) (*models.User, error) {
	ret := _m.Called(ctx, email, passwordHash, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateUnconfirmedUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.User, error)); ok {
		return rf(ctx, email, passwordHash, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.User); ok {
		r0 = rf(ctx, email, passwordHash, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, passwordHash, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_CreateUnconfirmedUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUnconfirmedUser'
type MockUserRepository_CreateUnconfirmedUser_Call struct {
	*mock.Call
}

// CreateUnconfirmedUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash string
//   - name string
func (_e *MockUserRepository_Expecter) CreateUnconfirmedUser(ctx interface{}, email interface{}, passwordHash interface{}, name interface{}) *MockUserRepository_CreateUnconfirmedUser_Call {
	return &MockUserRepository_CreateUnconfirmedUser_Call{Call: _e.mock.On("CreateUnconfirmedUser", ctx, email, passwordHash, name)}
}

func (_c *MockUserRepository_CreateUnconfirmedUser_Call) Run(run func(ctx context.Context, email string, passwordHash string, name string)) *MockUserRepository_CreateUnconfirmedUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUserRepository_CreateUnconfirmedUser_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_CreateUnconfirmedUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_CreateUnconfirmedUser_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.User, error)) *MockUserRepository_CreateUnconfirmedUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateUser provides a mock function with given fields: ctx, email, googleID, displayName, avatarURL
func (_m *MockUserRepository) GetOrCreateUser(ctx context.Context, email string, googleID string, displayName string, avatarURL string) (*models.User, error) {
	ret := _m.Called(ctx, email, googleID, displayName, avatarURL)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*models.User, error)); ok {
		return rf(ctx, email, googleID, displayName, avatarURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *models.User); ok {
		r0 = rf(ctx, email, googleID, displayName, avatarURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, email, googleID, displayName, avatarURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetOrCreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateUser'
type MockUserRepository_GetOrCreateUser_Call struct {
	*mock.Call
}

// GetOrCreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - googleID string
//   - displayName string
//   - avatarURL string
func (_e *MockUserRepository_Expecter) GetOrCreateUser(ctx interface{}, email interface{}, googleID interface{}, displayName interface{}, avatarURL interface{}) *MockUserRepository_GetOrCreateUser_Call {
	return &MockUserRepository_GetOrCreateUser_Call{Call: _e.mock.On("GetOrCreateUser", ctx, email, googleID, displayName, avatarURL)}
}

func (_c *MockUserRepository_GetOrCreateUser_Call) Run(run func(ctx context.Context, email string, googleID string, displayName string, avatarURL string)) *MockUserRepository_GetOrCreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetOrCreateUser_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_GetOrCreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetOrCreateUser_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*models.User, error)) *MockUserRepository_GetOrCreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEmailConfirmed provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) MarkEmailConfirmed(ctx context.Context, userID string) (*models.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailConfirmed")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_MarkEmailConfirmed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEmailConfirmed'
type MockUserRepository_MarkEmailConfirmed_Call struct {
	*mock.Call
}

// MarkEmailConfirmed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) MarkEmailConfirmed(ctx interface{}, userID interface{}) *MockUserRepository_MarkEmailConfirmed_Call {
	return &MockUserRepository_MarkEmailConfirmed_Call{Call: _e.mock.On("MarkEmailConfirmed", ctx, userID)}
}

func (_c *MockUserRepository_MarkEmailConfirmed_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_MarkEmailConfirmed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_MarkEmailConfirmed_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_MarkEmailConfirmed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_MarkEmailConfirmed_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockUserRepository_MarkEmailConfirmed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePasswordAndClearConfirmation provides a mock function with given fields: ctx, email, passwordHash, name
func (_m *MockUserRepository) UpdatePasswordAndClearConfirmation(ctx context.Context, email string, passwordHash string, name string) (*models.User, error) {
	ret := _m.Called(ctx, email, passwordHash, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasswordAndClearConfirmation")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.User, error)); ok {
		return rf(ctx, email, passwordHash, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.User); ok {
		r0 = rf(ctx, email, passwordHash, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, passwordHash, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_UpdatePasswordAndClearConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasswordAndClearConfirmation'
type MockUserRepository_UpdatePasswordAndClearConfirmation_Call struct {
	*mock.Call
}

// UpdatePasswordAndClearConfirmation is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash string
//   - name string
func (_e *MockUserRepository_Expecter) UpdatePasswordAndClearConfirmation(ctx interface{}, email interface{}, passwordHash interface{}, name interface{}) *MockUserRepository_UpdatePasswordAndClearConfirmation_Call {
	return &MockUserRepository_UpdatePasswordAndClearConfirmation_Call{Call: _e.mock.On("UpdatePasswordAndClearConfirmation", ctx, email, passwordHash, name)}
}

func (_c *MockUserRepository_UpdatePasswordAndClearConfirmation_Call) Run(run func(ctx context.Context, email string, passwordHash string, name string)) *MockUserRepository_UpdatePasswordAndClearConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUserRepository_UpdatePasswordAndClearConfirmation_Call) Return(_a0 *models.User, _a1 error) *MockUserRepository_UpdatePasswordAndClearConfirmation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_UpdatePasswordAndClearConfirmation_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.User, error)) *MockUserRepository_UpdatePasswordAndClearConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
