// Code generated by mockery. DO NOT EDIT.

package handler

import (
	context "context"

	auth "github.com/franciskershaw/crockpot-go/internal/auth"

	mock "github.com/stretchr/testify/mock"

	oauth2 "golang.org/x/oauth2"
)

// MockOAuthManager is an autogenerated mock type for the OAuthManager type
type MockOAuthManager struct {
	mock.Mock
}

type MockOAuthManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthManager) EXPECT() *MockOAuthManager_Expecter {
	return &MockOAuthManager_Expecter{mock: &_m.Mock}
}

// ExchangeCodeForToken provides a mock function with given fields: ctx, code
func (_m *MockOAuthManager) ExchangeCodeForToken(ctx context.Context, code string) (*oauth2.Token, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCodeForToken")
	}

	var r0 *oauth2.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*oauth2.Token, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *oauth2.Token); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthManager_ExchangeCodeForToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCodeForToken'
type MockOAuthManager_ExchangeCodeForToken_Call struct {
	*mock.Call
}

// ExchangeCodeForToken is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockOAuthManager_Expecter) ExchangeCodeForToken(ctx interface{}, code interface{}) *MockOAuthManager_ExchangeCodeForToken_Call {
	return &MockOAuthManager_ExchangeCodeForToken_Call{Call: _e.mock.On("ExchangeCodeForToken", ctx, code)}
}

func (_c *MockOAuthManager_ExchangeCodeForToken_Call) Run(run func(ctx context.Context, code string)) *MockOAuthManager_ExchangeCodeForToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOAuthManager_ExchangeCodeForToken_Call) Return(_a0 *oauth2.Token, _a1 error) *MockOAuthManager_ExchangeCodeForToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthManager_ExchangeCodeForToken_Call) RunAndReturn(run func(context.Context, string) (*oauth2.Token, error)) *MockOAuthManager_ExchangeCodeForToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateState provides a mock function with no fields
func (_m *MockOAuthManager) GenerateState() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateState")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthManager_GenerateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateState'
type MockOAuthManager_GenerateState_Call struct {
	*mock.Call
}

// GenerateState is a helper method to define mock.On call
func (_e *MockOAuthManager_Expecter) GenerateState() *MockOAuthManager_GenerateState_Call {
	return &MockOAuthManager_GenerateState_Call{Call: _e.mock.On("GenerateState")}
}

func (_c *MockOAuthManager_GenerateState_Call) Run(run func()) *MockOAuthManager_GenerateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOAuthManager_GenerateState_Call) Return(_a0 string, _a1 error) *MockOAuthManager_GenerateState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthManager_GenerateState_Call) RunAndReturn(run func() (string, error)) *MockOAuthManager_GenerateState_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthURL provides a mock function with given fields: state
func (_m *MockOAuthManager) GetAuthURL(state string) string {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOAuthManager_GetAuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthURL'
type MockOAuthManager_GetAuthURL_Call struct {
	*mock.Call
}

// GetAuthURL is a helper method to define mock.On call
//   - state string
func (_e *MockOAuthManager_Expecter) GetAuthURL(state interface{}) *MockOAuthManager_GetAuthURL_Call {
	return &MockOAuthManager_GetAuthURL_Call{Call: _e.mock.On("GetAuthURL", state)}
}

func (_c *MockOAuthManager_GetAuthURL_Call) Run(run func(state string)) *MockOAuthManager_GetAuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOAuthManager_GetAuthURL_Call) Return(_a0 string) *MockOAuthManager_GetAuthURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOAuthManager_GetAuthURL_Call) RunAndReturn(run func(string) string) *MockOAuthManager_GetAuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateState provides a mock function with given fields: state
func (_m *MockOAuthManager) ValidateState(state string) bool {
	ret := _m.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for ValidateState")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(state)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockOAuthManager_ValidateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateState'
type MockOAuthManager_ValidateState_Call struct {
	*mock.Call
}

// ValidateState is a helper method to define mock.On call
//   - state string
func (_e *MockOAuthManager_Expecter) ValidateState(state interface{}) *MockOAuthManager_ValidateState_Call {
	return &MockOAuthManager_ValidateState_Call{Call: _e.mock.On("ValidateState", state)}
}

func (_c *MockOAuthManager_ValidateState_Call) Run(run func(state string)) *MockOAuthManager_ValidateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOAuthManager_ValidateState_Call) Return(_a0 bool) *MockOAuthManager_ValidateState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOAuthManager_ValidateState_Call) RunAndReturn(run func(string) bool) *MockOAuthManager_ValidateState_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyIDToken provides a mock function with given fields: ctx, token
func (_m *MockOAuthManager) VerifyIDToken(ctx context.Context, token *oauth2.Token) (*auth.IDTokenClaims, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyIDToken")
	}

	var r0 *auth.IDTokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *oauth2.Token) (*auth.IDTokenClaims, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *oauth2.Token) *auth.IDTokenClaims); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.IDTokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *oauth2.Token) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthManager_VerifyIDToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyIDToken'
type MockOAuthManager_VerifyIDToken_Call struct {
	*mock.Call
}

// VerifyIDToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *oauth2.Token
func (_e *MockOAuthManager_Expecter) VerifyIDToken(ctx interface{}, token interface{}) *MockOAuthManager_VerifyIDToken_Call {
	return &MockOAuthManager_VerifyIDToken_Call{Call: _e.mock.On("VerifyIDToken", ctx, token)}
}

func (_c *MockOAuthManager_VerifyIDToken_Call) Run(run func(ctx context.Context, token *oauth2.Token)) *MockOAuthManager_VerifyIDToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*oauth2.Token))
	})
	return _c
}

func (_c *MockOAuthManager_VerifyIDToken_Call) Return(_a0 *auth.IDTokenClaims, _a1 error) *MockOAuthManager_VerifyIDToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthManager_VerifyIDToken_Call) RunAndReturn(run func(context.Context, *oauth2.Token) (*auth.IDTokenClaims, error)) *MockOAuthManager_VerifyIDToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthManager creates a new instance of MockOAuthManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthManager {
	mock := &MockOAuthManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
