// Code generated by mockery. DO NOT EDIT.

package handler

import (
	context "context"

	models "github.com/franciskershaw/crockpot-go/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// CreateFamily provides a mock function with given fields: ctx, id, userID, tokenHash, expiresAt
func (_m *MockRefreshTokenRepository) CreateFamily(ctx context.Context, id string, userID string, tokenHash string, expiresAt time.Time) (*models.RefreshTokenFamily, error) {
	ret := _m.Called(ctx, id, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateFamily")
	}

	var r0 *models.RefreshTokenFamily
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) (*models.RefreshTokenFamily, error)); ok {
		return rf(ctx, id, userID, tokenHash, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) *models.RefreshTokenFamily); ok {
		r0 = rf(ctx, id, userID, tokenHash, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshTokenFamily)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, time.Time) error); ok {
		r1 = rf(ctx, id, userID, tokenHash, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_CreateFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFamily'
type MockRefreshTokenRepository_CreateFamily_Call struct {
	*mock.Call
}

// CreateFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
//   - tokenHash string
//   - expiresAt time.Time
func (_e *MockRefreshTokenRepository_Expecter) CreateFamily(ctx interface{}, id interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *MockRefreshTokenRepository_CreateFamily_Call {
	return &MockRefreshTokenRepository_CreateFamily_Call{Call: _e.mock.On("CreateFamily", ctx, id, userID, tokenHash, expiresAt)}
}

func (_c *MockRefreshTokenRepository_CreateFamily_Call) Run(run func(ctx context.Context, id string, userID string, tokenHash string, expiresAt time.Time)) *MockRefreshTokenRepository_CreateFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(time.Time))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_CreateFamily_Call) Return(_a0 *models.RefreshTokenFamily, _a1 error) *MockRefreshTokenRepository_CreateFamily_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_CreateFamily_Call) RunAndReturn(run func(context.Context, string, string, string, time.Time) (*models.RefreshTokenFamily, error)) *MockRefreshTokenRepository_CreateFamily_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStaleFamiliesForUser provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) DeleteStaleFamiliesForUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStaleFamiliesForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStaleFamiliesForUser'
type MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call struct {
	*mock.Call
}

// DeleteStaleFamiliesForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRefreshTokenRepository_Expecter) DeleteStaleFamiliesForUser(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call {
	return &MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call{Call: _e.mock.On("DeleteStaleFamiliesForUser", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call) Run(run func(ctx context.Context, userID string)) *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call) Return(_a0 error) *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call) RunAndReturn(run func(context.Context, string) error) *MockRefreshTokenRepository_DeleteStaleFamiliesForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
