// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, attempts, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActiveEmailVerificationTokensForUser = `-- name: DeleteActiveEmailVerificationTokensForUser :exec
DELETE FROM email_verification_tokens
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteActiveEmailVerificationTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteActiveEmailVerificationTokensForUser, userID)
	return err
}

const findActiveEmailVerificationTokenByUserID = `-- name: FindActiveEmailVerificationTokenByUserID :one
SELECT id, user_id, token_hash, attempts, expires_at, used_at, created_at FROM email_verification_tokens
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) FindActiveEmailVerificationTokenByUserID(ctx context.Context, userID pgtype.UUID) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, findActiveEmailVerificationTokenByUserID, userID)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementEmailVerificationTokenAttempts = `-- name: IncrementEmailVerificationTokenAttempts :one
UPDATE email_verification_tokens
SET attempts = attempts + 1
WHERE id = $1
RETURNING id, user_id, token_hash, attempts, expires_at, used_at, created_at
`

func (q *Queries) IncrementEmailVerificationTokenAttempts(ctx context.Context, id pgtype.UUID) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, incrementEmailVerificationTokenAttempts, id)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :exec
UPDATE email_verification_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerificationTokenUsed, id)
	return err
}
