// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favourites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavourite = `-- name: AddFavourite :exec
INSERT INTO recipe_favourites (user_id, recipe_id) VALUES ($1, $2)
ON CONFLICT (user_id, recipe_id) DO NOTHING
`

type AddFavouriteParams struct {
	UserID   pgtype.UUID
	RecipeID pgtype.UUID
}

func (q *Queries) AddFavourite(ctx context.Context, arg AddFavouriteParams) error {
	_, err := q.db.Exec(ctx, addFavourite, arg.UserID, arg.RecipeID)
	return err
}

const countFavouriteRecipes = `-- name: CountFavouriteRecipes :one
SELECT count(*) FROM recipe_favourites WHERE user_id = $1
`

func (q *Queries) CountFavouriteRecipes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFavouriteRecipes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isRecipeFavourited = `-- name: IsRecipeFavourited :one
SELECT EXISTS (
    SELECT 1 FROM recipe_favourites WHERE user_id = $1 AND recipe_id = $2
)
`

type IsRecipeFavouritedParams struct {
	UserID   pgtype.UUID
	RecipeID pgtype.UUID
}

func (q *Queries) IsRecipeFavourited(ctx context.Context, arg IsRecipeFavouritedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRecipeFavourited, arg.UserID, arg.RecipeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFavouriteRecipes = `-- name: ListFavouriteRecipes :many
SELECT r.id, r.name, r.description, r.time_in_minutes, r.image_url, r.image_filename, r.instructions, r.notes, r.approved, r.serves, r.created_by_id, r.created_by_name, r.created_at, r.updated_at
FROM recipes r
JOIN recipe_favourites f ON f.recipe_id = r.id
WHERE f.user_id = $1
ORDER BY f.created_at DESC, r.id
LIMIT $2 OFFSET $3
`

type ListFavouriteRecipesParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListFavouriteRecipes(ctx context.Context, arg ListFavouriteRecipesParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listFavouriteRecipes, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TimeInMinutes,
			&i.ImageUrl,
			&i.ImageFilename,
			&i.Instructions,
			&i.Notes,
			&i.Approved,
			&i.Serves,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavouritedRecipeIDs = `-- name: ListFavouritedRecipeIDs :many
SELECT recipe_id FROM recipe_favourites
WHERE user_id = $1 AND recipe_id = ANY($2::uuid[])
`

type ListFavouritedRecipeIDsParams struct {
	UserID    pgtype.UUID
	RecipeIds []pgtype.UUID
}

func (q *Queries) ListFavouritedRecipeIDs(ctx context.Context, arg ListFavouritedRecipeIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listFavouritedRecipeIDs, arg.UserID, arg.RecipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var recipe_id pgtype.UUID
		if err := rows.Scan(&recipe_id); err != nil {
			return nil, err
		}
		items = append(items, recipe_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recipeVisibleToCaller = `-- name: RecipeVisibleToCaller :one
SELECT EXISTS (
    SELECT 1 FROM recipes r
    WHERE r.id = $1
      AND (r.approved OR $2::boolean OR r.created_by_id = $3::uuid)
)
`

type RecipeVisibleToCallerParams struct {
	ID            pgtype.UUID
	CallerIsAdmin bool
	CallerID      pgtype.UUID
}

func (q *Queries) RecipeVisibleToCaller(ctx context.Context, arg RecipeVisibleToCallerParams) (bool, error) {
	row := q.db.QueryRow(ctx, recipeVisibleToCaller, arg.ID, arg.CallerIsAdmin, arg.CallerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeFavourite = `-- name: RemoveFavourite :exec
DELETE FROM recipe_favourites WHERE user_id = $1 AND recipe_id = $2
`

type RemoveFavouriteParams struct {
	UserID   pgtype.UUID
	RecipeID pgtype.UUID
}

func (q *Queries) RemoveFavourite(ctx context.Context, arg RemoveFavouriteParams) error {
	_, err := q.db.Exec(ctx, removeFavourite, arg.UserID, arg.RecipeID)
	return err
}
