// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItemCategory = `-- name: CreateItemCategory :one
INSERT INTO item_categories (name, icon)
VALUES ($1, $2)
RETURNING id, name, icon, created_at, updated_at
`

type CreateItemCategoryParams struct {
	Name string
	Icon string
}

func (q *Queries) CreateItemCategory(ctx context.Context, arg CreateItemCategoryParams) (ItemCategory, error) {
	row := q.db.QueryRow(ctx, createItemCategory, arg.Name, arg.Icon)
	var i ItemCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItemCategory = `-- name: DeleteItemCategory :one
DELETE FROM item_categories
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteItemCategory(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteItemCategory, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const listItemCategories = `-- name: ListItemCategories :many
SELECT id, name, icon, created_at, updated_at FROM item_categories
ORDER BY name
`

func (q *Queries) ListItemCategories(ctx context.Context) ([]ItemCategory, error) {
	rows, err := q.db.Query(ctx, listItemCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemCategory
	for rows.Next() {
		var i ItemCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemCategory = `-- name: UpdateItemCategory :one
UPDATE item_categories
SET name = COALESCE(NULLIF($1::text, ''), name),
    icon = COALESCE(NULLIF($2::text, ''), icon),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, name, icon, created_at, updated_at
`

type UpdateItemCategoryParams struct {
	Name string
	Icon string
	ID   pgtype.UUID
}

func (q *Queries) UpdateItemCategory(ctx context.Context, arg UpdateItemCategoryParams) (ItemCategory, error) {
	row := q.db.QueryRow(ctx, updateItemCategory, arg.Name, arg.Icon, arg.ID)
	var i ItemCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
