// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (name, category_id)
VALUES ($1, $2)
RETURNING id, category_id, name, created_at, updated_at
`

type CreateItemParams struct {
	Name       string
	CategoryID pgtype.UUID
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, arg.Name, arg.CategoryID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createItemAllowedUnit = `-- name: CreateItemAllowedUnit :exec
INSERT INTO item_allowed_units (item_id, unit_id)
VALUES ($1, $2)
`

type CreateItemAllowedUnitParams struct {
	ItemID pgtype.UUID
	UnitID pgtype.UUID
}

func (q *Queries) CreateItemAllowedUnit(ctx context.Context, arg CreateItemAllowedUnitParams) error {
	_, err := q.db.Exec(ctx, createItemAllowedUnit, arg.ItemID, arg.UnitID)
	return err
}

const deleteItem = `-- name: DeleteItem :one
DELETE FROM items
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteItem(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteItem, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const deleteItemAllowedUnitsForItem = `-- name: DeleteItemAllowedUnitsForItem :exec
DELETE FROM item_allowed_units
WHERE item_id = $1
`

func (q *Queries) DeleteItemAllowedUnitsForItem(ctx context.Context, itemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemAllowedUnitsForItem, itemID)
	return err
}

const listItemAllowedUnitIDs = `-- name: ListItemAllowedUnitIDs :many
SELECT unit_id FROM item_allowed_units
WHERE item_id = $1
ORDER BY unit_id
`

func (q *Queries) ListItemAllowedUnitIDs(ctx context.Context, itemID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listItemAllowedUnitIDs, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var unit_id pgtype.UUID
		if err := rows.Scan(&unit_id); err != nil {
			return nil, err
		}
		items = append(items, unit_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemAllowedUnitIDsForItems = `-- name: ListItemAllowedUnitIDsForItems :many
SELECT item_id, unit_id FROM item_allowed_units
WHERE item_id = ANY($1::uuid[])
ORDER BY unit_id
`

func (q *Queries) ListItemAllowedUnitIDsForItems(ctx context.Context, itemIds []pgtype.UUID) ([]ItemAllowedUnit, error) {
	rows, err := q.db.Query(ctx, listItemAllowedUnitIDsForItems, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemAllowedUnit
	for rows.Next() {
		var i ItemAllowedUnit
		if err := rows.Scan(&i.ItemID, &i.UnitID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, category_id, name, created_at, updated_at FROM items
ORDER BY name
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET name = COALESCE(NULLIF($1::text, ''), name),
    category_id = COALESCE($2, category_id),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, category_id, name, created_at, updated_at
`

type UpdateItemParams struct {
	Name       string
	CategoryID pgtype.UUID
	ID         pgtype.UUID
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem, arg.Name, arg.CategoryID, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
