// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearMenuEntries = `-- name: ClearMenuEntries :exec
WITH cleared AS (
    DELETE FROM recipe_menu_entries
    WHERE recipe_menu_entries.recipe_menu_id IN (SELECT id FROM recipe_menus WHERE user_id = $1)
    RETURNING recipe_menu_id, recipe_id
)
INSERT INTO menu_history_events (recipe_menu_id, recipe_id, event_type)
SELECT recipe_menu_id, recipe_id, 'remove' FROM cleared
`

func (q *Queries) ClearMenuEntries(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearMenuEntries, userID)
	return err
}

const getMenuByUserID = `-- name: GetMenuByUserID :one
SELECT id FROM recipe_menus WHERE user_id = $1
`

func (q *Queries) GetMenuByUserID(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMenuByUserID, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrCreateMenu = `-- name: GetOrCreateMenu :one
INSERT INTO recipe_menus (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = excluded.user_id
RETURNING id
`

func (q *Queries) GetOrCreateMenu(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrCreateMenu, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listMenuEntries = `-- name: ListMenuEntries :many
SELECT rme.serves AS menu_serves, r.id, r.name, r.description, r.time_in_minutes, r.image_url, r.image_filename, r.instructions, r.notes, r.approved, r.serves, r.created_by_id, r.created_by_name, r.created_at, r.updated_at
FROM recipe_menu_entries rme
JOIN recipes r ON r.id = rme.recipe_id
WHERE rme.recipe_menu_id = $1
ORDER BY rme.created_at DESC
`

type ListMenuEntriesRow struct {
	MenuServes    int32
	ID            pgtype.UUID
	Name          string
	Description   pgtype.Text
	TimeInMinutes int32
	ImageUrl      pgtype.Text
	ImageFilename pgtype.Text
	Instructions  []string
	Notes         []string
	Approved      bool
	Serves        int32
	CreatedByID   pgtype.UUID
	CreatedByName pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListMenuEntries(ctx context.Context, recipeMenuID pgtype.UUID) ([]ListMenuEntriesRow, error) {
	rows, err := q.db.Query(ctx, listMenuEntries, recipeMenuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuEntriesRow
	for rows.Next() {
		var i ListMenuEntriesRow
		if err := rows.Scan(
			&i.MenuServes,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TimeInMinutes,
			&i.ImageUrl,
			&i.ImageFilename,
			&i.Instructions,
			&i.Notes,
			&i.Approved,
			&i.Serves,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMenuEntry = `-- name: RemoveMenuEntry :exec
WITH removed AS (
    DELETE FROM recipe_menu_entries
    WHERE recipe_menu_entries.recipe_menu_id = $1 AND recipe_menu_entries.recipe_id = $2
    RETURNING recipe_menu_id, recipe_id
)
INSERT INTO menu_history_events (recipe_menu_id, recipe_id, event_type)
SELECT recipe_menu_id, recipe_id, 'remove' FROM removed
`

type RemoveMenuEntryParams struct {
	RecipeMenuID pgtype.UUID
	RecipeID     pgtype.UUID
}

func (q *Queries) RemoveMenuEntry(ctx context.Context, arg RemoveMenuEntryParams) error {
	_, err := q.db.Exec(ctx, removeMenuEntry, arg.RecipeMenuID, arg.RecipeID)
	return err
}

const updateMenuEntryServes = `-- name: UpdateMenuEntryServes :execrows
UPDATE recipe_menu_entries
SET serves = $3
WHERE recipe_menu_id = $1 AND recipe_id = $2
`

type UpdateMenuEntryServesParams struct {
	RecipeMenuID pgtype.UUID
	RecipeID     pgtype.UUID
	Serves       int32
}

func (q *Queries) UpdateMenuEntryServes(ctx context.Context, arg UpdateMenuEntryServesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMenuEntryServes, arg.RecipeMenuID, arg.RecipeID, arg.Serves)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertMenuEntry = `-- name: UpsertMenuEntry :exec
WITH upserted AS (
    INSERT INTO recipe_menu_entries (recipe_menu_id, recipe_id, serves)
    VALUES ($1, $2, $3)
    ON CONFLICT (recipe_menu_id, recipe_id) DO UPDATE SET serves = excluded.serves
    RETURNING recipe_menu_id, recipe_id, (xmax = 0) AS inserted
)
INSERT INTO menu_history_events (recipe_menu_id, recipe_id, event_type)
SELECT recipe_menu_id, recipe_id, 'add' FROM upserted WHERE inserted
`

type UpsertMenuEntryParams struct {
	RecipeMenuID pgtype.UUID
	RecipeID     pgtype.UUID
	Serves       int32
}

// xmax = 0 is true only for a row this statement inserted, so a serves-only update records no event.
func (q *Queries) UpsertMenuEntry(ctx context.Context, arg UpsertMenuEntryParams) error {
	_, err := q.db.Exec(ctx, upsertMenuEntry, arg.RecipeMenuID, arg.RecipeID, arg.Serves)
	return err
}
