// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrate.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const migrateDeleteUsers = `-- name: MigrateDeleteUsers :exec
DELETE FROM users
WHERE id = ANY($1::uuid[])
   OR google_id = ANY($2::text[])
`

type MigrateDeleteUsersParams struct {
	Ids       []pgtype.UUID
	GoogleIds []string
}

func (q *Queries) MigrateDeleteUsers(ctx context.Context, arg MigrateDeleteUsersParams) error {
	_, err := q.db.Exec(ctx, migrateDeleteUsers, arg.Ids, arg.GoogleIds)
	return err
}

const migrateInsertItem = `-- name: MigrateInsertItem :exec
INSERT INTO items (id, name, category_id, created_at, updated_at)
VALUES (
    $1, $2, $3,
    $4, $5
)
`

type MigrateInsertItemParams struct {
	ID         pgtype.UUID
	Name       string
	CategoryID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) MigrateInsertItem(ctx context.Context, arg MigrateInsertItemParams) error {
	_, err := q.db.Exec(ctx, migrateInsertItem,
		arg.ID,
		arg.Name,
		arg.CategoryID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const migrateInsertItemAllowedUnit = `-- name: MigrateInsertItemAllowedUnit :exec
INSERT INTO item_allowed_units (item_id, unit_id)
VALUES ($1, $2)
`

type MigrateInsertItemAllowedUnitParams struct {
	ItemID pgtype.UUID
	UnitID pgtype.UUID
}

func (q *Queries) MigrateInsertItemAllowedUnit(ctx context.Context, arg MigrateInsertItemAllowedUnitParams) error {
	_, err := q.db.Exec(ctx, migrateInsertItemAllowedUnit, arg.ItemID, arg.UnitID)
	return err
}

const migrateInsertMenuHistoryBaseline = `-- name: MigrateInsertMenuHistoryBaseline :exec
INSERT INTO menu_history_baseline
    (recipe_menu_id, recipe_id, times_added_to_menu, first_added_to_menu, last_added_to_menu, last_removed_from_menu)
SELECT rm.id, $1, $2, $3, $4, $5
FROM recipe_menus rm
WHERE rm.user_id = $6
`

type MigrateInsertMenuHistoryBaselineParams struct {
	RecipeID    pgtype.UUID
	TimesAdded  int32
	FirstAdded  pgtype.Timestamptz
	LastAdded   pgtype.Timestamptz
	LastRemoved pgtype.Timestamptz
	UserID      pgtype.UUID
}

func (q *Queries) MigrateInsertMenuHistoryBaseline(ctx context.Context, arg MigrateInsertMenuHistoryBaselineParams) error {
	_, err := q.db.Exec(ctx, migrateInsertMenuHistoryBaseline,
		arg.RecipeID,
		arg.TimesAdded,
		arg.FirstAdded,
		arg.LastAdded,
		arg.LastRemoved,
		arg.UserID,
	)
	return err
}

const migrateInsertRecipe = `-- name: MigrateInsertRecipe :exec
INSERT INTO recipes (
    id, name, time_in_minutes, image_url, image_filename,
    instructions, notes, approved, serves,
    created_by_id, created_by_name, created_at, updated_at
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8, $9,
    $10, $11,
    $12, $13
)
`

type MigrateInsertRecipeParams struct {
	ID            pgtype.UUID
	Name          string
	TimeInMinutes int32
	ImageUrl      pgtype.Text
	ImageFilename pgtype.Text
	Instructions  []string
	Notes         []string
	Approved      bool
	Serves        int32
	CreatedByID   pgtype.UUID
	CreatedByName pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) MigrateInsertRecipe(ctx context.Context, arg MigrateInsertRecipeParams) error {
	_, err := q.db.Exec(ctx, migrateInsertRecipe,
		arg.ID,
		arg.Name,
		arg.TimeInMinutes,
		arg.ImageUrl,
		arg.ImageFilename,
		arg.Instructions,
		arg.Notes,
		arg.Approved,
		arg.Serves,
		arg.CreatedByID,
		arg.CreatedByName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const migrateInsertRecipeCategoryLink = `-- name: MigrateInsertRecipeCategoryLink :exec
INSERT INTO recipe_categories_recipes (recipe_id, category_id)
VALUES ($1, $2)
`

type MigrateInsertRecipeCategoryLinkParams struct {
	RecipeID   pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) MigrateInsertRecipeCategoryLink(ctx context.Context, arg MigrateInsertRecipeCategoryLinkParams) error {
	_, err := q.db.Exec(ctx, migrateInsertRecipeCategoryLink, arg.RecipeID, arg.CategoryID)
	return err
}

const migrateInsertRecipeIngredient = `-- name: MigrateInsertRecipeIngredient :exec
INSERT INTO recipe_ingredients (recipe_id, item_id, unit_id, quantity, position)
VALUES (
    $1, $2, $3,
    $4, $5
)
`

type MigrateInsertRecipeIngredientParams struct {
	RecipeID pgtype.UUID
	ItemID   pgtype.UUID
	UnitID   pgtype.UUID
	Quantity pgtype.Numeric
	Position int16
}

func (q *Queries) MigrateInsertRecipeIngredient(ctx context.Context, arg MigrateInsertRecipeIngredientParams) error {
	_, err := q.db.Exec(ctx, migrateInsertRecipeIngredient,
		arg.RecipeID,
		arg.ItemID,
		arg.UnitID,
		arg.Quantity,
		arg.Position,
	)
	return err
}

const migrateInsertRecipeMenu = `-- name: MigrateInsertRecipeMenu :exec
INSERT INTO recipe_menus (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) MigrateInsertRecipeMenu(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, migrateInsertRecipeMenu, userID)
	return err
}

const migrateInsertUser = `-- name: MigrateInsertUser :exec

INSERT INTO users (
    id, email, google_id, name, image, role, email_verified_at,
    created_at, updated_at
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9
)
`

type MigrateInsertUserParams struct {
	ID              pgtype.UUID
	Email           string
	GoogleID        pgtype.Text
	Name            pgtype.Text
	Image           pgtype.Text
	Role            string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Queries for cmd/migrate-data only. Every column is explicit (id, timestamps,
// created_by_name) so the one-off import can preserve the source's real values
// instead of the API's server-assigned defaults. See docs/handoffs/CROC-024.md.
func (q *Queries) MigrateInsertUser(ctx context.Context, arg MigrateInsertUserParams) error {
	_, err := q.db.Exec(ctx, migrateInsertUser,
		arg.ID,
		arg.Email,
		arg.GoogleID,
		arg.Name,
		arg.Image,
		arg.Role,
		arg.EmailVerifiedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const migrateTruncate = `-- name: MigrateTruncate :exec
TRUNCATE
    recipe_categories_recipes,
    recipe_ingredients,
    recipe_favourites,
    recipe_menu_entries,
    menu_history_baseline,
    menu_history_events,
    shopping_list_items,
    shopping_list_dismissed_items,
    item_allowed_units,
    recipes,
    items
RESTART IDENTITY
`

// Every table that FKs into recipes or items is named explicitly (no CASCADE)
// so a future table added against those references fails this loudly instead of
// being wiped silently. TestMigrateTruncateCoversEveryReferencingTable fails if
// this list drifts from the schema.
func (q *Queries) MigrateTruncate(ctx context.Context) error {
	_, err := q.db.Exec(ctx, migrateTruncate)
	return err
}
