// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	Attempts  int32
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Item struct {
	ID         pgtype.UUID
	CategoryID pgtype.UUID
	Name       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ItemAllowedUnit struct {
	ItemID pgtype.UUID
	UnitID pgtype.UUID
}

type ItemCategory struct {
	ID        pgtype.UUID
	Name      string
	Icon      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type MenuHistoryEntry struct {
	ID                  pgtype.UUID
	RecipeMenuID        pgtype.UUID
	RecipeID            pgtype.UUID
	TimesAddedToMenu    int32
	FirstAddedToMenu    pgtype.Timestamptz
	LastAddedToMenu     pgtype.Timestamptz
	LastRemovedFromMenu pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Recipe struct {
	ID            pgtype.UUID
	Name          string
	Description   pgtype.Text
	TimeInMinutes int32
	ImageUrl      pgtype.Text
	ImageFilename pgtype.Text
	Instructions  []string
	Notes         []string
	Approved      bool
	Serves        int32
	CreatedByID   pgtype.UUID
	CreatedByName pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type RecipeCategoriesRecipe struct {
	RecipeID   pgtype.UUID
	CategoryID pgtype.UUID
}

type RecipeCategory struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RecipeFavourite struct {
	UserID   pgtype.UUID
	RecipeID pgtype.UUID
}

type RecipeIngredient struct {
	ID       pgtype.UUID
	RecipeID pgtype.UUID
	ItemID   pgtype.UUID
	UnitID   pgtype.UUID
	Quantity pgtype.Numeric
}

type RecipeMenu struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RecipeMenuEntry struct {
	ID           pgtype.UUID
	RecipeMenuID pgtype.UUID
	RecipeID     pgtype.UUID
	Serves       int32
}

type RefreshToken struct {
	ID                     pgtype.UUID
	UserID                 pgtype.UUID
	TokenHash              string
	PreviousTokenHash      pgtype.Text
	PreviousTokenRotatedAt pgtype.Timestamptz
	ExpiresAt              pgtype.Timestamptz
	RevokedAt              pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
}

type ShoppingList struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ShoppingListItem struct {
	ID             pgtype.UUID
	ShoppingListID pgtype.UUID
	ItemID         pgtype.UUID
	UnitID         pgtype.UUID
	Quantity       pgtype.Numeric
	Obtained       bool
	IsManual       bool
}

type Unit struct {
	ID           pgtype.UUID
	Name         string
	Abbreviation string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	GoogleID        pgtype.Text
	PasswordHash    pgtype.Text
	Email           string
	Name            pgtype.Text
	Image           pgtype.Text
	Role            string
	EmailVerifiedAt pgtype.Timestamptz
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
