// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecipes = `-- name: CountRecipes :one
SELECT count(*)
FROM recipes r
WHERE (
        r.approved
        OR $1::boolean
        OR ($2::uuid IS NOT NULL AND r.created_by_id = $2::uuid)
    )
    AND (
        NOT $3::boolean
        OR ($2::uuid IS NOT NULL AND r.created_by_id = $2::uuid)
    )
    AND ($4::text = '' OR r.name ILIKE '%' || $4::text || '%')
    AND ($5::int = 0 OR r.time_in_minutes >= $5::int)
    AND ($6::int = 0 OR r.time_in_minutes <= $6::int)
    AND (
        cardinality($7::uuid[]) = 0
        OR NOT EXISTS (
            SELECT 1 FROM recipe_categories_recipes x
            WHERE x.recipe_id = r.id AND x.category_id = ANY($7::uuid[])
        )
    )
    AND (
        (
            cardinality($8::uuid[]) = 0
            AND cardinality($9::uuid[]) = 0
        )
        OR EXISTS (
            SELECT 1 FROM recipe_categories_recipes x
            WHERE x.recipe_id = r.id AND x.category_id = ANY($8::uuid[])
        )
        OR EXISTS (
            SELECT 1 FROM recipe_ingredients x
            WHERE x.recipe_id = r.id AND x.item_id = ANY($9::uuid[])
        )
    )
`

type CountRecipesParams struct {
	CallerIsAdmin      bool
	CallerID           pgtype.UUID
	OnlyMine           bool
	NameQuery          string
	MinTime            int32
	MaxTime            int32
	ExcludeCategoryIds []pgtype.UUID
	IncludeCategoryIds []pgtype.UUID
	IngredientIds      []pgtype.UUID
}

func (q *Queries) CountRecipes(ctx context.Context, arg CountRecipesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipes,
		arg.CallerIsAdmin,
		arg.CallerID,
		arg.OnlyMine,
		arg.NameQuery,
		arg.MinTime,
		arg.MaxTime,
		arg.ExcludeCategoryIds,
		arg.IncludeCategoryIds,
		arg.IngredientIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecipesByCreator = `-- name: CountRecipesByCreator :one
SELECT count(*) FROM recipes
WHERE created_by_id = $1
`

func (q *Queries) CountRecipesByCreator(ctx context.Context, createdByID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipesByCreator, createdByID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (
    name,
    time_in_minutes,
    serves,
    instructions,
    notes,
    image_url,
    image_filename,
    approved,
    created_by_id,
    created_by_name
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    (SELECT name FROM users WHERE id = $9)
)
RETURNING id, name, description, time_in_minutes, image_url, image_filename, instructions, notes, approved, serves, created_by_id, created_by_name, created_at, updated_at
`

type CreateRecipeParams struct {
	Name          string
	TimeInMinutes int32
	Serves        int32
	Instructions  []string
	Notes         []string
	ImageUrl      pgtype.Text
	ImageFilename pgtype.Text
	Approved      bool
	CreatedByID   pgtype.UUID
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe,
		arg.Name,
		arg.TimeInMinutes,
		arg.Serves,
		arg.Instructions,
		arg.Notes,
		arg.ImageUrl,
		arg.ImageFilename,
		arg.Approved,
		arg.CreatedByID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TimeInMinutes,
		&i.ImageUrl,
		&i.ImageFilename,
		&i.Instructions,
		&i.Notes,
		&i.Approved,
		&i.Serves,
		&i.CreatedByID,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecipeCategoryLink = `-- name: CreateRecipeCategoryLink :exec
INSERT INTO recipe_categories_recipes (recipe_id, category_id)
VALUES ($1, $2)
`

type CreateRecipeCategoryLinkParams struct {
	RecipeID   pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) CreateRecipeCategoryLink(ctx context.Context, arg CreateRecipeCategoryLinkParams) error {
	_, err := q.db.Exec(ctx, createRecipeCategoryLink, arg.RecipeID, arg.CategoryID)
	return err
}

const createRecipeIngredient = `-- name: CreateRecipeIngredient :exec
INSERT INTO recipe_ingredients (recipe_id, item_id, unit_id, quantity, position)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRecipeIngredientParams struct {
	RecipeID pgtype.UUID
	ItemID   pgtype.UUID
	UnitID   pgtype.UUID
	Quantity pgtype.Numeric
	Position int16
}

func (q *Queries) CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) error {
	_, err := q.db.Exec(ctx, createRecipeIngredient,
		arg.RecipeID,
		arg.ItemID,
		arg.UnitID,
		arg.Quantity,
		arg.Position,
	)
	return err
}

const getRecipeForReader = `-- name: GetRecipeForReader :one
SELECT r.id, r.name, r.description, r.time_in_minutes, r.image_url, r.image_filename, r.instructions, r.notes, r.approved, r.serves, r.created_by_id, r.created_by_name, r.created_at, r.updated_at
FROM recipes r
WHERE r.id = $1
    AND (
        r.approved
        OR $2::boolean
        OR ($3::uuid IS NOT NULL AND r.created_by_id = $3::uuid)
    )
`

type GetRecipeForReaderParams struct {
	ID            pgtype.UUID
	CallerIsAdmin bool
	CallerID      pgtype.UUID
}

func (q *Queries) GetRecipeForReader(ctx context.Context, arg GetRecipeForReaderParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeForReader, arg.ID, arg.CallerIsAdmin, arg.CallerID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TimeInMinutes,
		&i.ImageUrl,
		&i.ImageFilename,
		&i.Instructions,
		&i.Notes,
		&i.Approved,
		&i.Serves,
		&i.CreatedByID,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeTimeRange = `-- name: GetRecipeTimeRange :one
SELECT
    COALESCE(MIN(time_in_minutes), 0)::int AS min_time,
    COALESCE(MAX(time_in_minutes), 120)::int AS max_time
FROM recipes
WHERE approved
`

type GetRecipeTimeRangeRow struct {
	MinTime int32
	MaxTime int32
}

func (q *Queries) GetRecipeTimeRange(ctx context.Context) (GetRecipeTimeRangeRow, error) {
	row := q.db.QueryRow(ctx, getRecipeTimeRange)
	var i GetRecipeTimeRangeRow
	err := row.Scan(&i.MinTime, &i.MaxTime)
	return i, err
}

const listRecipeCardCategories = `-- name: ListRecipeCardCategories :many
SELECT rcr.recipe_id, rc.id, rc.name
FROM recipe_categories_recipes rcr
JOIN recipe_categories rc ON rc.id = rcr.category_id
WHERE rcr.recipe_id = ANY($1::uuid[])
ORDER BY rc.name
`

type ListRecipeCardCategoriesRow struct {
	RecipeID pgtype.UUID
	ID       pgtype.UUID
	Name     string
}

func (q *Queries) ListRecipeCardCategories(ctx context.Context, recipeIds []pgtype.UUID) ([]ListRecipeCardCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listRecipeCardCategories, recipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeCardCategoriesRow
	for rows.Next() {
		var i ListRecipeCardCategoriesRow
		if err := rows.Scan(&i.RecipeID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeDetailCategories = `-- name: ListRecipeDetailCategories :many
SELECT rc.id, rc.name
FROM recipe_categories_recipes rcr
JOIN recipe_categories rc ON rc.id = rcr.category_id
WHERE rcr.recipe_id = $1
ORDER BY rc.name
`

type ListRecipeDetailCategoriesRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListRecipeDetailCategories(ctx context.Context, recipeID pgtype.UUID) ([]ListRecipeDetailCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listRecipeDetailCategories, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeDetailCategoriesRow
	for rows.Next() {
		var i ListRecipeDetailCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
SELECT item_id, unit_id, quantity FROM recipe_ingredients
WHERE recipe_id = $1
ORDER BY position
`

type ListRecipeIngredientsRow struct {
	ItemID   pgtype.UUID
	UnitID   pgtype.UUID
	Quantity pgtype.Numeric
}

func (q *Queries) ListRecipeIngredients(ctx context.Context, recipeID pgtype.UUID) ([]ListRecipeIngredientsRow, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeIngredientsRow
	for rows.Next() {
		var i ListRecipeIngredientsRow
		if err := rows.Scan(&i.ItemID, &i.UnitID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredientsHydrated = `-- name: ListRecipeIngredientsHydrated :many
SELECT
    ri.item_id,
    i.name AS item_name,
    i.category_id AS item_category_id,
    ic.name AS item_category_name,
    ri.unit_id,
    u.abbreviation AS unit_abbreviation,
    ri.quantity
FROM recipe_ingredients ri
JOIN items i ON i.id = ri.item_id
JOIN item_categories ic ON ic.id = i.category_id
LEFT JOIN units u ON u.id = ri.unit_id
WHERE ri.recipe_id = $1
ORDER BY ri.position
`

type ListRecipeIngredientsHydratedRow struct {
	ItemID           pgtype.UUID
	ItemName         string
	ItemCategoryID   pgtype.UUID
	ItemCategoryName string
	UnitID           pgtype.UUID
	UnitAbbreviation pgtype.Text
	Quantity         pgtype.Numeric
}

func (q *Queries) ListRecipeIngredientsHydrated(ctx context.Context, recipeID pgtype.UUID) ([]ListRecipeIngredientsHydratedRow, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredientsHydrated, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeIngredientsHydratedRow
	for rows.Next() {
		var i ListRecipeIngredientsHydratedRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.ItemCategoryID,
			&i.ItemCategoryName,
			&i.UnitID,
			&i.UnitAbbreviation,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
WITH candidates AS (
    SELECT
        r.id, r.name, r.description, r.time_in_minutes, r.image_url, r.image_filename, r.instructions, r.notes, r.approved, r.serves, r.created_by_id, r.created_by_name, r.created_at, r.updated_at,
        (SELECT count(*) FROM recipe_ingredients x WHERE x.recipe_id = r.id)::int AS total_ingredient_count,
        (
            SELECT count(*) FROM recipe_ingredients x
            WHERE x.recipe_id = r.id AND x.item_id = ANY($6::uuid[])
        )::int AS matched_ingredient_count,
        (
            SELECT count(*) FROM recipe_categories_recipes x
            WHERE x.recipe_id = r.id AND x.category_id = ANY($7::uuid[])
        )::int AS matched_category_count
    FROM recipes r
    WHERE (
            r.approved
            OR $8::boolean
            OR ($9::uuid IS NOT NULL AND r.created_by_id = $9::uuid)
        )
        AND (
            NOT $10::boolean
            OR ($9::uuid IS NOT NULL AND r.created_by_id = $9::uuid)
        )
        AND ($11::text = '' OR r.name ILIKE '%' || $11::text || '%')
        AND ($12::int = 0 OR r.time_in_minutes >= $12::int)
        AND ($13::int = 0 OR r.time_in_minutes <= $13::int)
        AND (
            cardinality($14::uuid[]) = 0
            OR NOT EXISTS (
                SELECT 1 FROM recipe_categories_recipes x
                WHERE x.recipe_id = r.id AND x.category_id = ANY($14::uuid[])
            )
        )
        AND (
            NOT $1::boolean
            OR EXISTS (
                SELECT 1 FROM recipe_categories_recipes x
                WHERE x.recipe_id = r.id AND x.category_id = ANY($7::uuid[])
            )
            OR EXISTS (
                SELECT 1 FROM recipe_ingredients x
                WHERE x.recipe_id = r.id AND x.item_id = ANY($6::uuid[])
            )
        )
), scored AS (
    SELECT
        candidates.id, candidates.name, candidates.description, candidates.time_in_minutes, candidates.image_url, candidates.image_filename, candidates.instructions, candidates.notes, candidates.approved, candidates.serves, candidates.created_by_id, candidates.created_by_name, candidates.created_at, candidates.updated_at, candidates.total_ingredient_count, candidates.matched_ingredient_count, candidates.matched_category_count,
        (CASE
            WHEN NOT $1::boolean
                THEN 0::float8
            ELSE
                (
                    COALESCE(matched_ingredient_count::float8 / NULLIF(total_ingredient_count, 0), 0)
                        * cardinality($6::uuid[])
                    + matched_category_count::float8
                ) / NULLIF(cardinality($6::uuid[]) + cardinality($7::uuid[]), 0)
        END)::float8 AS score
    FROM candidates
)
SELECT scored.id, scored.name, scored.description, scored.time_in_minutes, scored.image_url, scored.image_filename, scored.instructions, scored.notes, scored.approved, scored.serves, scored.created_by_id, scored.created_by_name, scored.created_at, scored.updated_at, scored.total_ingredient_count, scored.matched_ingredient_count, scored.matched_category_count, scored.score
FROM scored
ORDER BY
    (CASE
        WHEN $1::boolean
            THEN scored.score
    END) DESC,
    (CASE
        WHEN $2::boolean
            THEN md5(scored.id::text || $3::text)
    END) ASC,
    scored.created_at DESC,
    scored.id
LIMIT $5::int OFFSET $4::int
`

type ListRecipesParams struct {
	HasScoreSignal     bool
	IsUnfiltered       bool
	Seed               string
	ResultOffset       int32
	ResultLimit        int32
	IngredientIds      []pgtype.UUID
	IncludeCategoryIds []pgtype.UUID
	CallerIsAdmin      bool
	CallerID           pgtype.UUID
	OnlyMine           bool
	NameQuery          string
	MinTime            int32
	MaxTime            int32
	ExcludeCategoryIds []pgtype.UUID
}

type ListRecipesRow struct {
	ID                     pgtype.UUID
	Name                   string
	Description            pgtype.Text
	TimeInMinutes          int32
	ImageUrl               pgtype.Text
	ImageFilename          pgtype.Text
	Instructions           []string
	Notes                  []string
	Approved               bool
	Serves                 int32
	CreatedByID            pgtype.UUID
	CreatedByName          pgtype.Text
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	TotalIngredientCount   int32
	MatchedIngredientCount int32
	MatchedCategoryCount   int32
	Score                  float64
}

func (q *Queries) ListRecipes(ctx context.Context, arg ListRecipesParams) ([]ListRecipesRow, error) {
	rows, err := q.db.Query(ctx, listRecipes,
		arg.HasScoreSignal,
		arg.IsUnfiltered,
		arg.Seed,
		arg.ResultOffset,
		arg.ResultLimit,
		arg.IngredientIds,
		arg.IncludeCategoryIds,
		arg.CallerIsAdmin,
		arg.CallerID,
		arg.OnlyMine,
		arg.NameQuery,
		arg.MinTime,
		arg.MaxTime,
		arg.ExcludeCategoryIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipesRow
	for rows.Next() {
		var i ListRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TimeInMinutes,
			&i.ImageUrl,
			&i.ImageFilename,
			&i.Instructions,
			&i.Notes,
			&i.Approved,
			&i.Serves,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalIngredientCount,
			&i.MatchedIngredientCount,
			&i.MatchedCategoryCount,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
