// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecipesByCreator = `-- name: CountRecipesByCreator :one
SELECT count(*) FROM recipes
WHERE created_by_id = $1
`

func (q *Queries) CountRecipesByCreator(ctx context.Context, createdByID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipesByCreator, createdByID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecipesUsingImage = `-- name: CountRecipesUsingImage :one
SELECT count(*) FROM recipes
WHERE image_filename = $1 AND id <> $2
`

type CountRecipesUsingImageParams struct {
	ImageFilename pgtype.Text
	ExcludeID     pgtype.UUID
}

func (q *Queries) CountRecipesUsingImage(ctx context.Context, arg CountRecipesUsingImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipesUsingImage, arg.ImageFilename, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecipesWithImage = `-- name: CountRecipesWithImage :one
SELECT count(*) FROM recipes WHERE image_filename = $1
`

func (q *Queries) CountRecipesWithImage(ctx context.Context, imageFilename pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipesWithImage, imageFilename)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (
    name,
    description,
    time_in_minutes,
    serves,
    instructions,
    notes,
    image_url,
    image_filename,
    approved,
    created_by_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, name, description, time_in_minutes, image_url, image_filename, instructions, notes, approved, serves, created_by_id, created_at, updated_at
`

type CreateRecipeParams struct {
	Name          string
	Description   pgtype.Text
	TimeInMinutes int32
	Serves        int32
	Instructions  []string
	Notes         []string
	ImageUrl      pgtype.Text
	ImageFilename pgtype.Text
	Approved      bool
	CreatedByID   pgtype.UUID
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe,
		arg.Name,
		arg.Description,
		arg.TimeInMinutes,
		arg.Serves,
		arg.Instructions,
		arg.Notes,
		arg.ImageUrl,
		arg.ImageFilename,
		arg.Approved,
		arg.CreatedByID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TimeInMinutes,
		&i.ImageUrl,
		&i.ImageFilename,
		&i.Instructions,
		&i.Notes,
		&i.Approved,
		&i.Serves,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecipeCategoryLink = `-- name: CreateRecipeCategoryLink :exec
INSERT INTO recipe_categories_recipes (recipe_id, category_id)
VALUES ($1, $2)
`

type CreateRecipeCategoryLinkParams struct {
	RecipeID   pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) CreateRecipeCategoryLink(ctx context.Context, arg CreateRecipeCategoryLinkParams) error {
	_, err := q.db.Exec(ctx, createRecipeCategoryLink, arg.RecipeID, arg.CategoryID)
	return err
}

const createRecipeIngredient = `-- name: CreateRecipeIngredient :exec
INSERT INTO recipe_ingredients (recipe_id, item_id, unit_id, quantity, position)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRecipeIngredientParams struct {
	RecipeID pgtype.UUID
	ItemID   pgtype.UUID
	UnitID   pgtype.UUID
	Quantity pgtype.Numeric
	Position int16
}

func (q *Queries) CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) error {
	_, err := q.db.Exec(ctx, createRecipeIngredient,
		arg.RecipeID,
		arg.ItemID,
		arg.UnitID,
		arg.Quantity,
		arg.Position,
	)
	return err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes WHERE id = $1
`

func (q *Queries) DeleteRecipe(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecipe, id)
	return err
}

const deleteRecipeCategoryLinks = `-- name: DeleteRecipeCategoryLinks :exec
DELETE FROM recipe_categories_recipes WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeCategoryLinks(ctx context.Context, recipeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecipeCategoryLinks, recipeID)
	return err
}

const deleteRecipeIngredients = `-- name: DeleteRecipeIngredients :exec
DELETE FROM recipe_ingredients WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeIngredients(ctx context.Context, recipeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecipeIngredients, recipeID)
	return err
}

const getRecipeForReader = `-- name: GetRecipeForReader :one
SELECT r.id, r.name, r.description, r.time_in_minutes, r.image_url, r.image_filename, r.instructions, r.notes, r.approved, r.serves, r.created_by_id, r.created_at, r.updated_at
FROM recipes r
WHERE r.id = $1
    AND recipe_visible_to(r.approved, r.created_by_id, $2::uuid, $3::boolean)
`

type GetRecipeForReaderParams struct {
	ID            pgtype.UUID
	CallerID      pgtype.UUID
	CallerIsAdmin bool
}

func (q *Queries) GetRecipeForReader(ctx context.Context, arg GetRecipeForReaderParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeForReader, arg.ID, arg.CallerID, arg.CallerIsAdmin)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TimeInMinutes,
		&i.ImageUrl,
		&i.ImageFilename,
		&i.Instructions,
		&i.Notes,
		&i.Approved,
		&i.Serves,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeForWrite = `-- name: GetRecipeForWrite :one
SELECT id, created_by_id, approved, image_url, image_filename
FROM recipes
WHERE id = $1
FOR UPDATE
`

type GetRecipeForWriteRow struct {
	ID            pgtype.UUID
	CreatedByID   pgtype.UUID
	Approved      bool
	ImageUrl      pgtype.Text
	ImageFilename pgtype.Text
}

// FOR UPDATE makes a concurrent menu add (its FK check takes KEY SHARE) finish before Delete reads who holds the recipe.
func (q *Queries) GetRecipeForWrite(ctx context.Context, id pgtype.UUID) (GetRecipeForWriteRow, error) {
	row := q.db.QueryRow(ctx, getRecipeForWrite, id)
	var i GetRecipeForWriteRow
	err := row.Scan(
		&i.ID,
		&i.CreatedByID,
		&i.Approved,
		&i.ImageUrl,
		&i.ImageFilename,
	)
	return i, err
}

const getRecipeTimeRange = `-- name: GetRecipeTimeRange :one
SELECT
    COALESCE(MIN(time_in_minutes), 0)::int AS min_time,
    COALESCE(MAX(time_in_minutes), 120)::int AS max_time
FROM recipes
WHERE approved
`

type GetRecipeTimeRangeRow struct {
	MinTime int32
	MaxTime int32
}

func (q *Queries) GetRecipeTimeRange(ctx context.Context) (GetRecipeTimeRangeRow, error) {
	row := q.db.QueryRow(ctx, getRecipeTimeRange)
	var i GetRecipeTimeRangeRow
	err := row.Scan(&i.MinTime, &i.MaxTime)
	return i, err
}

const listRecipeCardCategories = `-- name: ListRecipeCardCategories :many
SELECT rcr.recipe_id, rc.id, rc.name
FROM recipe_categories_recipes rcr
JOIN recipe_categories rc ON rc.id = rcr.category_id
WHERE rcr.recipe_id = ANY($1::uuid[])
ORDER BY rc.name
`

type ListRecipeCardCategoriesRow struct {
	RecipeID pgtype.UUID
	ID       pgtype.UUID
	Name     string
}

func (q *Queries) ListRecipeCardCategories(ctx context.Context, recipeIds []pgtype.UUID) ([]ListRecipeCardCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listRecipeCardCategories, recipeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeCardCategoriesRow
	for rows.Next() {
		var i ListRecipeCardCategoriesRow
		if err := rows.Scan(&i.RecipeID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeDetailCategories = `-- name: ListRecipeDetailCategories :many
SELECT rc.id, rc.name
FROM recipe_categories_recipes rcr
JOIN recipe_categories rc ON rc.id = rcr.category_id
WHERE rcr.recipe_id = $1
ORDER BY rc.name
`

type ListRecipeDetailCategoriesRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListRecipeDetailCategories(ctx context.Context, recipeID pgtype.UUID) ([]ListRecipeDetailCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listRecipeDetailCategories, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeDetailCategoriesRow
	for rows.Next() {
		var i ListRecipeDetailCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredientsHydrated = `-- name: ListRecipeIngredientsHydrated :many
SELECT
    ri.item_id,
    i.name AS item_name,
    i.category_id AS item_category_id,
    ic.name AS item_category_name,
    ri.unit_id,
    u.abbreviation AS unit_abbreviation,
    ri.quantity
FROM recipe_ingredients ri
JOIN items i ON i.id = ri.item_id
JOIN item_categories ic ON ic.id = i.category_id
LEFT JOIN units u ON u.id = ri.unit_id
WHERE ri.recipe_id = $1
ORDER BY ri.position
`

type ListRecipeIngredientsHydratedRow struct {
	ItemID           pgtype.UUID
	ItemName         string
	ItemCategoryID   pgtype.UUID
	ItemCategoryName string
	UnitID           pgtype.UUID
	UnitAbbreviation pgtype.Text
	Quantity         pgtype.Numeric
}

func (q *Queries) ListRecipeIngredientsHydrated(ctx context.Context, recipeID pgtype.UUID) ([]ListRecipeIngredientsHydratedRow, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredientsHydrated, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeIngredientsHydratedRow
	for rows.Next() {
		var i ListRecipeIngredientsHydratedRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.ItemCategoryID,
			&i.ItemCategoryName,
			&i.UnitID,
			&i.UnitAbbreviation,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
WITH candidates AS (
    SELECT
        r.id, r.name, r.description, r.time_in_minutes, r.image_url, r.image_filename, r.instructions, r.notes, r.approved, r.serves, r.created_by_id, r.created_at, r.updated_at,
        (SELECT count(*) FROM recipe_ingredients x WHERE x.recipe_id = r.id)::int AS total_ingredient_count,
        (
            SELECT count(*) FROM recipe_ingredients x
            WHERE x.recipe_id = r.id AND x.item_id = ANY($6::uuid[])
        )::int AS matched_ingredient_count,
        (
            SELECT count(*) FROM recipe_categories_recipes x
            WHERE x.recipe_id = r.id AND x.category_id = ANY($7::uuid[])
        )::int AS matched_category_count
    FROM recipes r
    WHERE recipe_visible_to(r.approved, r.created_by_id, $8::uuid, $9::boolean)
        AND (
            NOT $10::boolean
            OR ($8::uuid IS NOT NULL AND r.created_by_id = $8::uuid)
        )
        AND ($11::text = '' OR r.name ILIKE '%' || $11::text || '%')
        AND ($12::int = 0 OR r.time_in_minutes >= $12::int)
        AND ($13::int = 0 OR r.time_in_minutes <= $13::int)
        AND (
            cardinality($14::uuid[]) = 0
            OR NOT EXISTS (
                SELECT 1 FROM recipe_categories_recipes x
                WHERE x.recipe_id = r.id AND x.category_id = ANY($14::uuid[])
            )
        )
        AND (
            NOT $1::boolean
            OR EXISTS (
                SELECT 1 FROM recipe_categories_recipes x
                WHERE x.recipe_id = r.id AND x.category_id = ANY($7::uuid[])
            )
            OR EXISTS (
                SELECT 1 FROM recipe_ingredients x
                WHERE x.recipe_id = r.id AND x.item_id = ANY($6::uuid[])
            )
        )
), scored AS (
    SELECT
        candidates.id, candidates.name, candidates.description, candidates.time_in_minutes, candidates.image_url, candidates.image_filename, candidates.instructions, candidates.notes, candidates.approved, candidates.serves, candidates.created_by_id, candidates.created_at, candidates.updated_at, candidates.total_ingredient_count, candidates.matched_ingredient_count, candidates.matched_category_count,
        (CASE
            WHEN NOT $1::boolean
                THEN 0::float8
            ELSE
                (
                    COALESCE(matched_ingredient_count::float8 / NULLIF(total_ingredient_count, 0), 0)
                        * cardinality($6::uuid[])
                    + matched_category_count::float8
                ) / NULLIF(cardinality($6::uuid[]) + cardinality($7::uuid[]), 0)
        END)::float8 AS score
    FROM candidates
)
SELECT scored.id, scored.name, scored.description, scored.time_in_minutes, scored.image_url, scored.image_filename, scored.instructions, scored.notes, scored.approved, scored.serves, scored.created_by_id, scored.created_at, scored.updated_at, scored.total_ingredient_count, scored.matched_ingredient_count, scored.matched_category_count, scored.score, count(*) OVER ()::int AS total
FROM scored
ORDER BY
    (CASE
        WHEN $1::boolean
            THEN scored.score
    END) DESC,
    (CASE
        WHEN $2::boolean
            THEN md5(scored.id::text || $3::text)
    END) ASC,
    scored.created_at DESC,
    scored.id
LIMIT $5::int OFFSET $4::int
`

type ListRecipesParams struct {
	HasScoreSignal     bool
	IsUnfiltered       bool
	Seed               string
	ResultOffset       int32
	ResultLimit        int32
	IngredientIds      []pgtype.UUID
	IncludeCategoryIds []pgtype.UUID
	CallerID           pgtype.UUID
	CallerIsAdmin      bool
	OnlyMine           bool
	NameQuery          string
	MinTime            int32
	MaxTime            int32
	ExcludeCategoryIds []pgtype.UUID
}

type ListRecipesRow struct {
	ID                     pgtype.UUID
	Name                   string
	Description            pgtype.Text
	TimeInMinutes          int32
	ImageUrl               pgtype.Text
	ImageFilename          pgtype.Text
	Instructions           []string
	Notes                  []string
	Approved               bool
	Serves                 int32
	CreatedByID            pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	TotalIngredientCount   int32
	MatchedIngredientCount int32
	MatchedCategoryCount   int32
	Score                  float64
	Total                  int32
}

func (q *Queries) ListRecipes(ctx context.Context, arg ListRecipesParams) ([]ListRecipesRow, error) {
	rows, err := q.db.Query(ctx, listRecipes,
		arg.HasScoreSignal,
		arg.IsUnfiltered,
		arg.Seed,
		arg.ResultOffset,
		arg.ResultLimit,
		arg.IngredientIds,
		arg.IncludeCategoryIds,
		arg.CallerID,
		arg.CallerIsAdmin,
		arg.OnlyMine,
		arg.NameQuery,
		arg.MinTime,
		arg.MaxTime,
		arg.ExcludeCategoryIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipesRow
	for rows.Next() {
		var i ListRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TimeInMinutes,
			&i.ImageUrl,
			&i.ImageFilename,
			&i.Instructions,
			&i.Notes,
			&i.Approved,
			&i.Serves,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalIngredientCount,
			&i.MatchedIngredientCount,
			&i.MatchedCategoryCount,
			&i.Score,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnapprovedRecipesForWriteByCreator = `-- name: ListUnapprovedRecipesForWriteByCreator :many
SELECT id, image_filename
FROM recipes
WHERE created_by_id = $1 AND NOT approved
ORDER BY id
FOR UPDATE
`

type ListUnapprovedRecipesForWriteByCreatorRow struct {
	ID            pgtype.UUID
	ImageFilename pgtype.Text
}

// FOR UPDATE re-checks approved after any wait, so a recipe approved concurrently drops out instead of being deleted.
func (q *Queries) ListUnapprovedRecipesForWriteByCreator(ctx context.Context, creatorID pgtype.UUID) ([]ListUnapprovedRecipesForWriteByCreatorRow, error) {
	rows, err := q.db.Query(ctx, listUnapprovedRecipesForWriteByCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnapprovedRecipesForWriteByCreatorRow
	for rows.Next() {
		var i ListUnapprovedRecipesForWriteByCreatorRow
		if err := rows.Scan(&i.ID, &i.ImageFilename); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockImage = `-- name: LockImage :exec
SELECT pg_advisory_xact_lock(hashtext($1::text))
`

// Serialises concurrent drops of one shared image so the last one sees the others gone and reports it orphaned.
func (q *Queries) LockImage(ctx context.Context, imageFilename string) error {
	_, err := q.db.Exec(ctx, lockImage, imageFilename)
	return err
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes SET
    name = $1,
    description = $2,
    time_in_minutes = $3,
    serves = $4,
    instructions = $5,
    notes = $6,
    image_url = $7,
    image_filename = $8,
    approved = $9,
    updated_at = now()
WHERE id = $10
RETURNING id, name, description, time_in_minutes, image_url, image_filename, instructions, notes, approved, serves, created_by_id, created_at, updated_at
`

type UpdateRecipeParams struct {
	Name          string
	Description   pgtype.Text
	TimeInMinutes int32
	Serves        int32
	Instructions  []string
	Notes         []string
	ImageUrl      pgtype.Text
	ImageFilename pgtype.Text
	Approved      bool
	ID            pgtype.UUID
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe,
		arg.Name,
		arg.Description,
		arg.TimeInMinutes,
		arg.Serves,
		arg.Instructions,
		arg.Notes,
		arg.ImageUrl,
		arg.ImageFilename,
		arg.Approved,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TimeInMinutes,
		&i.ImageUrl,
		&i.ImageFilename,
		&i.Instructions,
		&i.Notes,
		&i.Approved,
		&i.Serves,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
