// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipe_categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecipeCategory = `-- name: CreateRecipeCategory :one
INSERT INTO recipe_categories (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateRecipeCategory(ctx context.Context, name string) (RecipeCategory, error) {
	row := q.db.QueryRow(ctx, createRecipeCategory, name)
	var i RecipeCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecipeCategory = `-- name: DeleteRecipeCategory :one
DELETE FROM recipe_categories
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteRecipeCategory(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteRecipeCategory, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const listRecipeCategories = `-- name: ListRecipeCategories :many
SELECT id, name, created_at, updated_at FROM recipe_categories
ORDER BY name
`

func (q *Queries) ListRecipeCategories(ctx context.Context) ([]RecipeCategory, error) {
	rows, err := q.db.Query(ctx, listRecipeCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecipeCategory
	for rows.Next() {
		var i RecipeCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipeCategory = `-- name: UpdateRecipeCategory :one
UPDATE recipe_categories
SET name = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdateRecipeCategoryParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpdateRecipeCategory(ctx context.Context, arg UpdateRecipeCategoryParams) (RecipeCategory, error) {
	row := q.db.QueryRow(ctx, updateRecipeCategory, arg.ID, arg.Name)
	var i RecipeCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
