// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshTokenFamily = `-- name: CreateRefreshTokenFamily :one
INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, previous_token_hash, previous_token_rotated_at, expires_at, revoked_at, created_at
`

type CreateRefreshTokenFamilyParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshTokenFamily(ctx context.Context, arg CreateRefreshTokenFamilyParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshTokenFamily,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.PreviousTokenHash,
		&i.PreviousTokenRotatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStaleRefreshTokenFamiliesForUser = `-- name: DeleteStaleRefreshTokenFamiliesForUser :exec
DELETE FROM refresh_tokens
WHERE user_id = $1 AND (revoked_at IS NOT NULL OR expires_at < CURRENT_TIMESTAMP)
`

func (q *Queries) DeleteStaleRefreshTokenFamiliesForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaleRefreshTokenFamiliesForUser, userID)
	return err
}

const revokeAllRefreshTokenFamiliesForUser = `-- name: RevokeAllRefreshTokenFamiliesForUser :exec
UPDATE refresh_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at >= CURRENT_TIMESTAMP
`

func (q *Queries) RevokeAllRefreshTokenFamiliesForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokenFamiliesForUser, userID)
	return err
}
