// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: regulars.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRegular = `-- name: DeleteRegular :execrows
DELETE FROM regular_items
WHERE id = $1 AND user_id = $2
`

type DeleteRegularParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteRegular(ctx context.Context, arg DeleteRegularParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRegular, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRegularHydrated = `-- name: GetRegularHydrated :one
SELECT
    r.id,
    r.item_id,
    i.name AS item_name,
    i.category_id,
    ic.name AS category_name,
    r.unit_id,
    u.abbreviation AS unit_abbreviation,
    r.quantity
FROM regular_items r
JOIN items i ON i.id = r.item_id
JOIN item_categories ic ON ic.id = i.category_id
LEFT JOIN units u ON u.id = r.unit_id
WHERE r.id = $1 AND r.user_id = $2
`

type GetRegularHydratedParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetRegularHydratedRow struct {
	ID               pgtype.UUID
	ItemID           pgtype.UUID
	ItemName         string
	CategoryID       pgtype.UUID
	CategoryName     string
	UnitID           pgtype.UUID
	UnitAbbreviation pgtype.Text
	Quantity         pgtype.Numeric
}

func (q *Queries) GetRegularHydrated(ctx context.Context, arg GetRegularHydratedParams) (GetRegularHydratedRow, error) {
	row := q.db.QueryRow(ctx, getRegularHydrated, arg.ID, arg.UserID)
	var i GetRegularHydratedRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.ItemName,
		&i.CategoryID,
		&i.CategoryName,
		&i.UnitID,
		&i.UnitAbbreviation,
		&i.Quantity,
	)
	return i, err
}

const getRegularItemID = `-- name: GetRegularItemID :one
SELECT item_id FROM regular_items
WHERE id = $1 AND user_id = $2
`

type GetRegularItemIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetRegularItemID(ctx context.Context, arg GetRegularItemIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRegularItemID, arg.ID, arg.UserID)
	var item_id pgtype.UUID
	err := row.Scan(&item_id)
	return item_id, err
}

const insertRegularWithinLimit = `-- name: InsertRegularWithinLimit :one
INSERT INTO regular_items (user_id, item_id, unit_id, quantity)
SELECT $1, $2, $3, $4
WHERE (SELECT count(*) FROM regular_items WHERE user_id = $1) < $5::bigint
RETURNING id
`

type InsertRegularWithinLimitParams struct {
	UserID      pgtype.UUID
	ItemID      pgtype.UUID
	UnitID      pgtype.UUID
	Quantity    pgtype.Numeric
	MaxRegulars int64
}

func (q *Queries) InsertRegularWithinLimit(ctx context.Context, arg InsertRegularWithinLimitParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRegularWithinLimit,
		arg.UserID,
		arg.ItemID,
		arg.UnitID,
		arg.Quantity,
		arg.MaxRegulars,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listRegularsHydrated = `-- name: ListRegularsHydrated :many
SELECT
    r.id,
    r.item_id,
    i.name AS item_name,
    i.category_id,
    ic.name AS category_name,
    r.unit_id,
    u.abbreviation AS unit_abbreviation,
    r.quantity
FROM regular_items r
JOIN items i ON i.id = r.item_id
JOIN item_categories ic ON ic.id = i.category_id
LEFT JOIN units u ON u.id = r.unit_id
WHERE r.user_id = $1
ORDER BY ic.name, i.name
`

type ListRegularsHydratedRow struct {
	ID               pgtype.UUID
	ItemID           pgtype.UUID
	ItemName         string
	CategoryID       pgtype.UUID
	CategoryName     string
	UnitID           pgtype.UUID
	UnitAbbreviation pgtype.Text
	Quantity         pgtype.Numeric
}

func (q *Queries) ListRegularsHydrated(ctx context.Context, userID pgtype.UUID) ([]ListRegularsHydratedRow, error) {
	rows, err := q.db.Query(ctx, listRegularsHydrated, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegularsHydratedRow
	for rows.Next() {
		var i ListRegularsHydratedRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.ItemName,
			&i.CategoryID,
			&i.CategoryName,
			&i.UnitID,
			&i.UnitAbbreviation,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegular = `-- name: UpdateRegular :execrows
UPDATE regular_items
SET unit_id = $1, quantity = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $3 AND user_id = $4
`

type UpdateRegularParams struct {
	UnitID   pgtype.UUID
	Quantity pgtype.Numeric
	ID       pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) UpdateRegular(ctx context.Context, arg UpdateRegularParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRegular,
		arg.UnitID,
		arg.Quantity,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
