// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shopping_list.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateMenuIngredients = `-- name: AggregateMenuIngredients :many
WITH base_units AS (
    SELECT
        (SELECT id FROM units WHERE name = 'grams') AS grams_id,
        (SELECT id FROM units WHERE name = 'milliliters') AS milliliters_id
), expanded AS (
    SELECT
        ri.item_id,
        ri.unit_id,
        ri.quantity,
        (rme.serves::numeric / r.serves::numeric) AS scale,
        u.dimension,
        u.base_factor,
        CASE u.dimension
            WHEN 'mass' THEN base_units.grams_id
            WHEN 'volume' THEN base_units.milliliters_id
        END AS base_unit_id
    FROM recipe_menu_entries rme
    JOIN recipes r ON r.id = rme.recipe_id
    JOIN recipe_ingredients ri ON ri.recipe_id = r.id
    LEFT JOIN units u ON u.id = ri.unit_id
    CROSS JOIN base_units
    WHERE rme.recipe_menu_id = $1
)
SELECT
    item_id,
    COALESCE(base_unit_id, unit_id)::uuid AS unit_id,
    SUM(quantity * scale * COALESCE(base_factor, 1))::numeric(10, 2) AS quantity
FROM expanded
GROUP BY item_id, COALESCE(base_unit_id, unit_id)
`

type AggregateMenuIngredientsRow struct {
	ItemID   pgtype.UUID
	UnitID   pgtype.UUID
	Quantity pgtype.Numeric
}

func (q *Queries) AggregateMenuIngredients(ctx context.Context, recipeMenuID pgtype.UUID) ([]AggregateMenuIngredientsRow, error) {
	rows, err := q.db.Query(ctx, aggregateMenuIngredients, recipeMenuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateMenuIngredientsRow
	for rows.Next() {
		var i AggregateMenuIngredientsRow
		if err := rows.Scan(&i.ItemID, &i.UnitID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteObsoleteShoppingListItems = `-- name: DeleteObsoleteShoppingListItems :exec
DELETE FROM shopping_list_items sli
WHERE sli.shopping_list_id = $1
    AND NOT sli.is_manual
    AND NOT EXISTS (
        SELECT 1
        FROM (
            SELECT
                unnest($2::uuid[]) AS item_id,
                unnest($3::uuid[]) AS unit_id
        ) t
        WHERE t.item_id = sli.item_id AND t.unit_id IS NOT DISTINCT FROM sli.unit_id
    )
`

type DeleteObsoleteShoppingListItemsParams struct {
	ShoppingListID pgtype.UUID
	ItemIds        []pgtype.UUID
	UnitIds        []pgtype.UUID
}

func (q *Queries) DeleteObsoleteShoppingListItems(ctx context.Context, arg DeleteObsoleteShoppingListItemsParams) error {
	_, err := q.db.Exec(ctx, deleteObsoleteShoppingListItems, arg.ShoppingListID, arg.ItemIds, arg.UnitIds)
	return err
}

const deleteStaleDismissals = `-- name: DeleteStaleDismissals :exec
DELETE FROM shopping_list_dismissed_items d USING (
    SELECT
        unnest($1::uuid[]) AS item_id,
        unnest($2::uuid[]) AS unit_id,
        unnest($3::numeric[]) AS quantity
) agg
WHERE d.shopping_list_id = $4
    AND d.item_id = agg.item_id
    AND d.unit_id IS NOT DISTINCT FROM agg.unit_id
    AND d.quantity_at_dismissal <> agg.quantity
`

type DeleteStaleDismissalsParams struct {
	ItemIds        []pgtype.UUID
	UnitIds        []pgtype.UUID
	Quantities     []pgtype.Numeric
	ShoppingListID pgtype.UUID
}

func (q *Queries) DeleteStaleDismissals(ctx context.Context, arg DeleteStaleDismissalsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleDismissals,
		arg.ItemIds,
		arg.UnitIds,
		arg.Quantities,
		arg.ShoppingListID,
	)
	return err
}

const findManualShoppingListItem = `-- name: FindManualShoppingListItem :one
SELECT id, quantity FROM shopping_list_items
WHERE shopping_list_id = $1
    AND item_id = $2
    AND unit_id IS NOT DISTINCT FROM $3::uuid
    AND is_manual
LIMIT 1
`

type FindManualShoppingListItemParams struct {
	ShoppingListID pgtype.UUID
	ItemID         pgtype.UUID
	UnitID         pgtype.UUID
}

type FindManualShoppingListItemRow struct {
	ID       pgtype.UUID
	Quantity pgtype.Numeric
}

func (q *Queries) FindManualShoppingListItem(ctx context.Context, arg FindManualShoppingListItemParams) (FindManualShoppingListItemRow, error) {
	row := q.db.QueryRow(ctx, findManualShoppingListItem, arg.ShoppingListID, arg.ItemID, arg.UnitID)
	var i FindManualShoppingListItemRow
	err := row.Scan(&i.ID, &i.Quantity)
	return i, err
}

const getOrCreateShoppingList = `-- name: GetOrCreateShoppingList :one
INSERT INTO shopping_lists (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = excluded.user_id
RETURNING id
`

func (q *Queries) GetOrCreateShoppingList(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrCreateShoppingList, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getShoppingListByUserID = `-- name: GetShoppingListByUserID :one
SELECT id FROM shopping_lists WHERE user_id = $1
`

func (q *Queries) GetShoppingListByUserID(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getShoppingListByUserID, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const incrementShoppingListItemQuantity = `-- name: IncrementShoppingListItemQuantity :exec
UPDATE shopping_list_items
SET quantity = quantity + $1
WHERE id = $2
`

type IncrementShoppingListItemQuantityParams struct {
	Delta pgtype.Numeric
	ID    pgtype.UUID
}

func (q *Queries) IncrementShoppingListItemQuantity(ctx context.Context, arg IncrementShoppingListItemQuantityParams) error {
	_, err := q.db.Exec(ctx, incrementShoppingListItemQuantity, arg.Delta, arg.ID)
	return err
}

const insertManualShoppingListItem = `-- name: InsertManualShoppingListItem :exec
INSERT INTO shopping_list_items (shopping_list_id, item_id, unit_id, quantity, obtained, is_manual)
VALUES ($1, $2, $3, $4, false, true)
`

type InsertManualShoppingListItemParams struct {
	ShoppingListID pgtype.UUID
	ItemID         pgtype.UUID
	UnitID         pgtype.UUID
	Quantity       pgtype.Numeric
}

func (q *Queries) InsertManualShoppingListItem(ctx context.Context, arg InsertManualShoppingListItemParams) error {
	_, err := q.db.Exec(ctx, insertManualShoppingListItem,
		arg.ShoppingListID,
		arg.ItemID,
		arg.UnitID,
		arg.Quantity,
	)
	return err
}

const insertNewShoppingListItems = `-- name: InsertNewShoppingListItems :exec
INSERT INTO shopping_list_items (shopping_list_id, item_id, unit_id, quantity, obtained, is_manual)
SELECT $1, agg.item_id, agg.unit_id, agg.quantity, false, false
FROM (
    SELECT
        unnest($2::uuid[]) AS item_id,
        unnest($3::uuid[]) AS unit_id,
        unnest($4::numeric[]) AS quantity
) agg
WHERE NOT EXISTS (
        SELECT 1 FROM shopping_list_items sli
        WHERE sli.shopping_list_id = $1
            AND sli.item_id = agg.item_id
            AND sli.unit_id IS NOT DISTINCT FROM agg.unit_id
            AND NOT sli.is_manual
    )
    AND NOT EXISTS (
        SELECT 1 FROM shopping_list_dismissed_items d
        WHERE d.shopping_list_id = $1
            AND d.item_id = agg.item_id
            AND d.unit_id IS NOT DISTINCT FROM agg.unit_id
            AND d.quantity_at_dismissal = agg.quantity
    )
`

type InsertNewShoppingListItemsParams struct {
	ShoppingListID pgtype.UUID
	ItemIds        []pgtype.UUID
	UnitIds        []pgtype.UUID
	Quantities     []pgtype.Numeric
}

func (q *Queries) InsertNewShoppingListItems(ctx context.Context, arg InsertNewShoppingListItemsParams) error {
	_, err := q.db.Exec(ctx, insertNewShoppingListItems,
		arg.ShoppingListID,
		arg.ItemIds,
		arg.UnitIds,
		arg.Quantities,
	)
	return err
}

const listShoppingListItemsHydrated = `-- name: ListShoppingListItemsHydrated :many
SELECT
    sli.id,
    sli.item_id,
    i.name AS item_name,
    i.category_id AS item_category_id,
    ic.name AS item_category_name,
    sli.unit_id,
    u.abbreviation AS unit_abbreviation,
    sli.quantity,
    sli.obtained,
    sli.is_manual
FROM shopping_list_items sli
JOIN items i ON i.id = sli.item_id
JOIN item_categories ic ON ic.id = i.category_id
LEFT JOIN units u ON u.id = sli.unit_id
WHERE sli.shopping_list_id = $1
ORDER BY ic.name, i.name
`

type ListShoppingListItemsHydratedRow struct {
	ID               pgtype.UUID
	ItemID           pgtype.UUID
	ItemName         string
	ItemCategoryID   pgtype.UUID
	ItemCategoryName string
	UnitID           pgtype.UUID
	UnitAbbreviation pgtype.Text
	Quantity         pgtype.Numeric
	Obtained         bool
	IsManual         bool
}

func (q *Queries) ListShoppingListItemsHydrated(ctx context.Context, shoppingListID pgtype.UUID) ([]ListShoppingListItemsHydratedRow, error) {
	rows, err := q.db.Query(ctx, listShoppingListItemsHydrated, shoppingListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShoppingListItemsHydratedRow
	for rows.Next() {
		var i ListShoppingListItemsHydratedRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.ItemName,
			&i.ItemCategoryID,
			&i.ItemCategoryName,
			&i.UnitID,
			&i.UnitAbbreviation,
			&i.Quantity,
			&i.Obtained,
			&i.IsManual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncShoppingListItemQuantities = `-- name: SyncShoppingListItemQuantities :exec
UPDATE shopping_list_items sli
SET quantity = agg.quantity
FROM (
    SELECT
        unnest($2::uuid[]) AS item_id,
        unnest($3::uuid[]) AS unit_id,
        unnest($4::numeric[]) AS quantity
) agg
WHERE sli.shopping_list_id = $1
    AND sli.item_id = agg.item_id
    AND sli.unit_id IS NOT DISTINCT FROM agg.unit_id
    AND NOT sli.is_manual
`

type SyncShoppingListItemQuantitiesParams struct {
	ShoppingListID pgtype.UUID
	ItemIds        []pgtype.UUID
	UnitIds        []pgtype.UUID
	Quantities     []pgtype.Numeric
}

func (q *Queries) SyncShoppingListItemQuantities(ctx context.Context, arg SyncShoppingListItemQuantitiesParams) error {
	_, err := q.db.Exec(ctx, syncShoppingListItemQuantities,
		arg.ShoppingListID,
		arg.ItemIds,
		arg.UnitIds,
		arg.Quantities,
	)
	return err
}

const updateShoppingListItem = `-- name: UpdateShoppingListItem :execrows
UPDATE shopping_list_items
SET obtained = COALESCE($1, obtained),
    quantity = COALESCE($2, quantity)
WHERE id = $3 AND shopping_list_id = $4
`

type UpdateShoppingListItemParams struct {
	Obtained       pgtype.Bool
	Quantity       pgtype.Numeric
	ID             pgtype.UUID
	ShoppingListID pgtype.UUID
}

func (q *Queries) UpdateShoppingListItem(ctx context.Context, arg UpdateShoppingListItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateShoppingListItem,
		arg.Obtained,
		arg.Quantity,
		arg.ID,
		arg.ShoppingListID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
