// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (name, abbreviation)
VALUES ($1, $2)
RETURNING id, name, abbreviation, created_at, updated_at
`

type CreateUnitParams struct {
	Name         string
	Abbreviation string
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, createUnit, arg.Name, arg.Abbreviation)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUnit = `-- name: DeleteUnit :one
DELETE FROM units
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteUnit(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteUnit, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const listUnits = `-- name: ListUnits :many
SELECT id, name, abbreviation, created_at, updated_at FROM units
ORDER BY name
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Abbreviation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE units
SET name = COALESCE(NULLIF($1::text, ''), name),
    abbreviation = COALESCE(NULLIF($2::text, ''), abbreviation),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, name, abbreviation, created_at, updated_at
`

type UpdateUnitParams struct {
	Name         string
	Abbreviation string
	ID           pgtype.UUID
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, updateUnit, arg.Name, arg.Abbreviation, arg.ID)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
