// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (email, google_id, name, image, email_verified_at, last_login_at)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, google_id, password_hash, email, name, image, role, email_verified_at, last_login_at, created_at, updated_at
`

type CreateGoogleUserParams struct {
	Email    string
	GoogleID pgtype.Text
	Name     pgtype.Text
	Image    pgtype.Text
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createGoogleUser,
		arg.Email,
		arg.GoogleID,
		arg.Name,
		arg.Image,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PasswordHash,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, password_hash, email, name, image, role, email_verified_at, last_login_at, created_at, updated_at FROM users
WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PasswordHash,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLoginProfile = `-- name: UpdateUserLoginProfile :one
UPDATE users
SET name = $2, image = $3, last_login_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, google_id, password_hash, email, name, image, role, email_verified_at, last_login_at, created_at, updated_at
`

type UpdateUserLoginProfileParams struct {
	ID    pgtype.UUID
	Name  pgtype.Text
	Image pgtype.Text
}

func (q *Queries) UpdateUserLoginProfile(ctx context.Context, arg UpdateUserLoginProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLoginProfile, arg.ID, arg.Name, arg.Image)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PasswordHash,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
