// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (email, google_id, name, image, email_verified_at, last_login_at)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, google_id, password_hash, email, name, image, role, email_verified_at, last_login_at, created_at, updated_at
`

type CreateGoogleUserParams struct {
	Email    string
	GoogleID pgtype.Text
	Name     pgtype.Text
	Image    pgtype.Text
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createGoogleUser,
		arg.Email,
		arg.GoogleID,
		arg.Name,
		arg.Image,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PasswordHash,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUnconfirmedUser = `-- name: CreateUnconfirmedUser :one
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, google_id, password_hash, email, name, image, role, email_verified_at, last_login_at, created_at, updated_at
`

type CreateUnconfirmedUserParams struct {
	Email        string
	PasswordHash pgtype.Text
	Name         pgtype.Text
}

func (q *Queries) CreateUnconfirmedUser(ctx context.Context, arg CreateUnconfirmedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUnconfirmedUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PasswordHash,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, google_id, password_hash, email, name, image, role, email_verified_at, last_login_at, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PasswordHash,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, password_hash, email, name, image, role, email_verified_at, last_login_at, created_at, updated_at FROM users
WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PasswordHash,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markUserEmailConfirmed = `-- name: MarkUserEmailConfirmed :one
UPDATE users
SET email_verified_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, google_id, password_hash, email, name, image, role, email_verified_at, last_login_at, created_at, updated_at
`

func (q *Queries) MarkUserEmailConfirmed(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserEmailConfirmed, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PasswordHash,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLoginProfile = `-- name: UpdateUserLoginProfile :one
UPDATE users
SET name = COALESCE(NULLIF($1::text, ''), name),
    image = COALESCE(NULLIF($2::text, ''), image),
    last_login_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, google_id, password_hash, email, name, image, role, email_verified_at, last_login_at, created_at, updated_at
`

type UpdateUserLoginProfileParams struct {
	DisplayName string
	AvatarUrl   string
	ID          pgtype.UUID
}

func (q *Queries) UpdateUserLoginProfile(ctx context.Context, arg UpdateUserLoginProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLoginProfile, arg.DisplayName, arg.AvatarUrl, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PasswordHash,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordAndName = `-- name: UpdateUserPasswordAndName :one
UPDATE users
SET password_hash = $2, name = $3, updated_at = CURRENT_TIMESTAMP
WHERE email = $1 AND email_verified_at IS NULL
RETURNING id, google_id, password_hash, email, name, image, role, email_verified_at, last_login_at, created_at, updated_at
`

type UpdateUserPasswordAndNameParams struct {
	Email        string
	PasswordHash pgtype.Text
	Name         pgtype.Text
}

func (q *Queries) UpdateUserPasswordAndName(ctx context.Context, arg UpdateUserPasswordAndNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordAndName, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.PasswordHash,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
